import type { Course } from '../types'

export const esCourse: Course = {
  id: 'es',
  name: 'Spanish',
  flag: '🇪🇸',
  ttsLang: 'es-ES',
  vocab: [
    // Unit 1 — survival
    { id: 'hola', lemma: 'hola', translation: 'hello' },
    { id: 'adios', lemma: 'adiós', translation: 'goodbye' },
    { id: 'si', lemma: 'sí', translation: 'yes' },
    { id: 'no', lemma: 'no', translation: 'no' },
    { id: 'gracias', lemma: 'gracias', translation: 'thank you' },
    { id: 'por-favor', lemma: 'por favor', translation: 'please' },
    { id: 'perdon', lemma: 'perdón', translation: 'excuse me / sorry' },
    { id: 'bien', lemma: 'bien', translation: 'well / good' },
    { id: 'mal', lemma: 'mal', translation: 'bad / badly' },
    { id: 'muy', lemma: 'muy', translation: 'very' },
    { id: 'esto', lemma: 'esto', translation: 'this' },
    { id: 'yo', lemma: 'yo', translation: 'I' },
    { id: 'tu', lemma: 'tú', translation: 'you (informal)' },
    { id: 'usted', lemma: 'usted', translation: 'you (formal)' },
    { id: 'quien', lemma: 'quién', translation: 'who' },
    { id: 'que', lemma: 'qué', translation: 'what' },
    { id: 'es', lemma: 'es', translation: 'is' },
    { id: 'buenos-dias', lemma: 'buenos días', translation: 'good morning' },
    // Unit 2 — I want / I have
    { id: 'quiero', lemma: 'querer', translation: 'to want', forms: ['quiero', 'quieres'], hint: 'quiero (I want)' },
    { id: 'tengo', lemma: 'tener', translation: 'to have', forms: ['tengo', 'tienes'], hint: 'tengo (I have)' },
    { id: 'agua', lemma: 'agua', translation: 'water' },
    { id: 'te', lemma: 'té', translation: 'tea' },
    { id: 'cafe', lemma: 'café', translation: 'coffee' },
    { id: 'pan', lemma: 'pan', translation: 'bread' },
    { id: 'zumo', lemma: 'zumo', translation: 'juice' },
    { id: 'leche', lemma: 'leche', translation: 'milk' },
    { id: 'queso', lemma: 'queso', translation: 'cheese' },
    { id: 'manzana', lemma: 'manzana', translation: 'apple' },
    { id: 'sopa', lemma: 'sopa', translation: 'soup' },
    { id: 'casa', lemma: 'casa', translation: 'house / home' },
    { id: 'gato', lemma: 'gato', translation: 'cat' },
    { id: 'perro', lemma: 'perro', translation: 'dog' },
    { id: 'libro', lemma: 'libro', translation: 'book' },
    { id: 'telefono', lemma: 'teléfono', translation: 'phone' },
    { id: 'dinero', lemma: 'dinero', translation: 'money' },
    { id: 'un', lemma: 'un / una', translation: 'a / an' },
    // Unit 3 — people & verbs
    { id: 'el', lemma: 'él', translation: 'he' },
    { id: 'ella', lemma: 'ella', translation: 'she' },
    { id: 'nosotros', lemma: 'nosotros', translation: 'we' },
    { id: 'ellos', lemma: 'ellos', translation: 'they' },
    { id: 'madre', lemma: 'madre', translation: 'mother', forms: ['mamá'] },
    { id: 'padre', lemma: 'padre', translation: 'father', forms: ['papá'] },
    { id: 'hermano', lemma: 'hermano', translation: 'brother' },
    { id: 'hermana', lemma: 'hermana', translation: 'sister' },
    { id: 'amigo', lemma: 'amigo', translation: 'friend' },
    { id: 'persona', lemma: 'persona', translation: 'person' },
    { id: 'se', lemma: 'saber', translation: 'to know', forms: ['sé', 'sabes'], hint: 'sé (I know)' },
    { id: 'entiendo', lemma: 'entender', translation: 'to understand', forms: ['entiendo', 'entiendes'], hint: 'entiendo (I understand)' },
    { id: 'hablo', lemma: 'hablar', translation: 'to speak', forms: ['hablo', 'hablas', 'habla'], hint: 'hablo (I speak)' },
    { id: 'amo', lemma: 'amar', translation: 'to love', forms: ['amo', 'amas'], hint: 'amo (I love)' },
    { id: 'vivo', lemma: 'vivir', translation: 'to live', forms: ['vivo', 'vives', 'vive'], hint: 'vivo (I live)' },
    { id: 'trabajo-v', lemma: 'trabajar', translation: 'to work', forms: ['trabajo', 'trabaja'], hint: 'trabajo (I work)' },
    { id: 'espanol', lemma: 'español', translation: 'Spanish' },
    { id: 'ingles', lemma: 'inglés', translation: 'English' },
    // Unit 4 — places
    { id: 'donde', lemma: 'dónde', translation: 'where' },
    { id: 'aqui', lemma: 'aquí', translation: 'here' },
    { id: 'alli', lemma: 'allí', translation: 'there' },
    { id: 'esta', lemma: 'está', translation: 'is (location)' },
    { id: 'escuela', lemma: 'escuela', translation: 'school' },
    { id: 'trabajo-n', lemma: 'trabajo', translation: 'work / job' },
    { id: 'tienda', lemma: 'tienda', translation: 'shop / store' },
    { id: 'ciudad', lemma: 'ciudad', translation: 'city' },
    { id: 'calle', lemma: 'calle', translation: 'street' },
    { id: 'espana', lemma: 'España', translation: 'Spain' },
    { id: 'madrid', lemma: 'Madrid', translation: 'Madrid' },
    { id: 'metro-es', lemma: 'metro', translation: 'metro / subway' },
    { id: 'bano', lemma: 'baño', translation: 'bathroom' },
    { id: 'estacion', lemma: 'estación', translation: 'station' },
    { id: 'restaurante', lemma: 'restaurante', translation: 'restaurant' },
    // Unit 5 — numbers & time
    { id: 'uno', lemma: 'uno', translation: 'one' },
    { id: 'dos', lemma: 'dos', translation: 'two' },
    { id: 'tres', lemma: 'tres', translation: 'three' },
    { id: 'cuatro', lemma: 'cuatro', translation: 'four' },
    { id: 'cinco', lemma: 'cinco', translation: 'five' },
    { id: 'seis', lemma: 'seis', translation: 'six' },
    { id: 'siete', lemma: 'siete', translation: 'seven' },
    { id: 'ocho', lemma: 'ocho', translation: 'eight' },
    { id: 'nueve', lemma: 'nueve', translation: 'nine' },
    { id: 'diez', lemma: 'diez', translation: 'ten' },
    { id: 'hora', lemma: 'hora', translation: 'hour / time' },
    { id: 'dia', lemma: 'día', translation: 'day' },
    { id: 'noche', lemma: 'noche', translation: 'night' },
    { id: 'manana-time', lemma: 'mañana', translation: 'morning / tomorrow' },
    { id: 'tarde', lemma: 'tarde', translation: 'afternoon / evening' },
    { id: 'hoy', lemma: 'hoy', translation: 'today' },
    { id: 'ahora', lemma: 'ahora', translation: 'now' },
    { id: 'cuando', lemma: 'cuándo', translation: 'when' },
    { id: 'cuanto', lemma: 'cuánto', translation: 'how much' },
    // Unit 6 — describing things
    { id: 'rojo', lemma: 'rojo', translation: 'red', forms: ['roja'] },
    { id: 'azul', lemma: 'azul', translation: 'blue' },
    { id: 'verde', lemma: 'verde', translation: 'green' },
    { id: 'amarillo', lemma: 'amarillo', translation: 'yellow', forms: ['amarilla'] },
    { id: 'negro', lemma: 'negro', translation: 'black', forms: ['negra'] },
    { id: 'blanco', lemma: 'blanco', translation: 'white', forms: ['blanca'] },
    { id: 'grande', lemma: 'grande', translation: 'big' },
    { id: 'pequeno', lemma: 'pequeño', translation: 'small', forms: ['pequeña'] },
    { id: 'nuevo', lemma: 'nuevo', translation: 'new', forms: ['nueva'] },
    { id: 'viejo', lemma: 'viejo', translation: 'old', forms: ['vieja'] },
    { id: 'bonito', lemma: 'bonito', translation: 'beautiful / pretty', forms: ['bonita'] },
    { id: 'rico', lemma: 'rico', translation: 'tasty / delicious', forms: ['rica'] },
    // Unit 7 — days & questions
    { id: 'lunes', lemma: 'lunes', translation: 'Monday' },
    { id: 'martes', lemma: 'martes', translation: 'Tuesday' },
    { id: 'miercoles', lemma: 'miércoles', translation: 'Wednesday' },
    { id: 'jueves', lemma: 'jueves', translation: 'Thursday' },
    { id: 'viernes', lemma: 'viernes', translation: 'Friday' },
    { id: 'sabado', lemma: 'sábado', translation: 'Saturday' },
    { id: 'domingo', lemma: 'domingo', translation: 'Sunday' },
    { id: 'semana', lemma: 'semana', translation: 'week' },
    { id: 'como', lemma: 'cómo', translation: 'how' },
    { id: 'por-que', lemma: 'por qué', translation: 'why' },
    { id: 'cual', lemma: 'cuál', translation: 'which' },
    // Unit 8 — food & shopping
    { id: 'carne', lemma: 'carne', translation: 'meat' },
    { id: 'pescado', lemma: 'pescado', translation: 'fish' },
    { id: 'fruta', lemma: 'fruta', translation: 'fruit' },
    { id: 'verduras', lemma: 'verduras', translation: 'vegetables' },
    { id: 'azucar', lemma: 'azúcar', translation: 'sugar' },
    { id: 'sal', lemma: 'sal', translation: 'salt' },
    { id: 'huevo', lemma: 'huevo', translation: 'egg' },
    { id: 'comprar', lemma: 'comprar', translation: 'to buy', forms: ['compro', 'compras'] },
    { id: 'cuesta', lemma: 'cuesta', translation: 'costs' },
    { id: 'caro', lemma: 'caro', translation: 'expensive', forms: ['cara'] },
    { id: 'barato', lemma: 'barato', translation: 'cheap', forms: ['barata'] },
    // Unit 9 — action verbs
    { id: 'ir', lemma: 'ir', translation: 'to go', forms: ['voy', 'vas', 'va'], hint: 'voy (I go)' },
    { id: 'comer', lemma: 'comer', translation: 'to eat', forms: ['como', 'comes', 'come'], hint: 'como (I eat)' },
    { id: 'beber', lemma: 'beber', translation: 'to drink', forms: ['bebo', 'bebes', 'bebe'], hint: 'bebo (I drink)' },
    { id: 'ver-verb', lemma: 'ver', translation: 'to see', forms: ['veo', 'ves', 've'], hint: 'veo (I see)' },
    { id: 'hacer', lemma: 'hacer', translation: 'to do / to make', forms: ['hago', 'haces', 'hace'], hint: 'hago (I do)' },
    { id: 'pensar', lemma: 'pensar', translation: 'to think', forms: ['pienso', 'piensas', 'piensa'], hint: 'pienso (I think)' },
    { id: 'dormir', lemma: 'dormir', translation: 'to sleep', forms: ['duermo', 'duermes', 'duerme'], hint: 'duermo (I sleep)' },
    { id: 'parque', lemma: 'parque', translation: 'park' },
    // Unit 10 — weather & feelings
    { id: 'tiempo', lemma: 'tiempo', translation: 'weather / time' },
    { id: 'frio', lemma: 'frío', translation: 'cold' },
    { id: 'calor', lemma: 'calor', translation: 'heat / hot' },
    { id: 'lluvia', lemma: 'lluvia', translation: 'rain' },
    { id: 'nieve', lemma: 'nieve', translation: 'snow' },
    { id: 'sol', lemma: 'sol', translation: 'sun' },
    { id: 'cansado', lemma: 'cansado', translation: 'tired', forms: ['cansada'] },
    { id: 'feliz', lemma: 'feliz', translation: 'happy' },
    { id: 'hambre', lemma: 'hambre', translation: 'hunger' },
    { id: 'sed', lemma: 'sed', translation: 'thirst' },
    // Unit 11 (A2) — preterite, reflexive verbs, gustar, ir a + infinitive, pronouns
    { id: 'ayer', lemma: 'ayer', translation: 'yesterday' },
    { id: 'estar', lemma: 'estar', translation: 'to be (location/state)', forms: ['estuve', 'estuviste', 'estuvo'] },
    { id: 'leer', lemma: 'leer', translation: 'to read', forms: ['leo', 'lees', 'lee', 'leí'] },
    { id: 'escribir', lemma: 'escribir', translation: 'to write', forms: ['escribo', 'escribes', 'escribe', 'escribí'] },
    { id: 'escuchar', lemma: 'escuchar', translation: 'to listen', forms: ['escucho', 'escuchas', 'escucha'] },
    { id: 'jugar', lemma: 'jugar', translation: 'to play', forms: ['juego', 'juegas', 'juega'] },
    { id: 'pelicula', lemma: 'película', translation: 'movie' },
    { id: 'musica', lemma: 'música', translation: 'music' },
    { id: 'levantarse', lemma: 'levantarse', translation: 'to get up', forms: ['me levanto', 'te levantas', 'se levanta'] },
    { id: 'ducharse', lemma: 'ducharse', translation: 'to shower', forms: ['me ducho', 'te duchas'] },
    { id: 'vestirse', lemma: 'vestirse', translation: 'to get dressed', forms: ['me visto', 'te vistes'] },
    { id: 'acostarse', lemma: 'acostarse', translation: 'to go to bed', forms: ['me acuesto', 'te acuestas'] },
    { id: 'apartamento', lemma: 'apartamento', translation: 'apartment' },
    { id: 'habitacion', lemma: 'habitación', translation: 'room / bedroom' },
    { id: 'cocina', lemma: 'cocina', translation: 'kitchen' },
    { id: 'entonces', lemma: 'entonces', translation: 'then / so' },
    { id: 'necesito', lemma: 'necesitar', translation: 'to need', forms: ['necesito', 'necesitas'], hint: 'necesito (I need)' },
    { id: 've', lemma: 've', translation: 'go! (imperative)' },
    { id: 'mira', lemma: 'mira', translation: 'look! (imperative)' },
    { id: 'di', lemma: 'di', translation: 'tell/say! (imperative)' },
    { id: 'gustar', lemma: 'gustar', translation: 'to please (me gusta = I like)' },
    { id: 'mas', lemma: 'más', translation: 'more' },
    { id: 'menos', lemma: 'menos', translation: 'less' },
    { id: 'lo', lemma: 'lo', translation: 'it / him (direct object)' },
    { id: 'le', lemma: 'le', translation: 'to him/her (indirect object)' },
    { id: 'enfermo', lemma: 'enfermo', translation: 'sick', forms: ['enferma'] },
    { id: 'dolor', lemma: 'dolor', translation: 'pain' },
    { id: 'medico', lemma: 'médico', translation: 'doctor', forms: ['médica'] },
    { id: 'estudiar', lemma: 'estudiar', translation: 'to study', forms: ['estudio', 'estudias', 'estudia'] },
    { id: 'oficina', lemma: 'oficina', translation: 'office' },
    { id: 'universidad', lemma: 'universidad', translation: 'university' },
    // Unit 12 (B1) — present subjunctive, perfect tenses, por vs. para
    { id: 'espero', lemma: 'esperar', translation: 'to hope / wait', forms: ['espero', 'esperas'], hint: 'espero (I hope)' },
    { id: 'ojala', lemma: 'ojalá', translation: 'hopefully / I wish', hint: 'ohala' },
    { id: 'venga', lemma: 'venga', translation: '(that) come (subjunctive of venir)', hint: 'venga' },
    { id: 'tenga', lemma: 'tenga', translation: '(that) have (subjunctive of tener)', hint: 'tenga' },
    { id: 'quizas', lemma: 'quizás', translation: 'maybe / perhaps', hint: 'kisas' },
    { id: 'he', lemma: 'haber', translation: 'to have (auxiliary)', forms: ['he', 'has', 'ha', 'hemos'], hint: 'e (I have - aux)' },
    { id: 'comido', lemma: 'comido', translation: 'eaten (past participle)', hint: 'komido' },
    { id: 'hablado', lemma: 'hablado', translation: 'spoken (past participle)', hint: 'ablado' },
    { id: 'vivido', lemma: 'vivido', translation: 'lived (past participle)', hint: 'bibido' },
    { id: 'por', lemma: 'por', translation: 'for / through / by', hint: 'por' },
    { id: 'para', lemma: 'para', translation: 'for / in order to', hint: 'para' },
    // Unit 13 (B2) — conditional mood, relative clauses, passive voice, reported speech
    { id: 'seria', lemma: 'sería', translation: 'would be (conditional of ser)', hint: 'seria' },
    { id: 'tendria', lemma: 'tendría', translation: 'would have (conditional of tener)', hint: 'tendria' },
    { id: 'gustaria', lemma: 'gustaría', translation: 'would like (conditional of gustar)', hint: 'gustaria' },
    { id: 'si-if', lemma: 'si', translation: 'if', hint: 'si (if)' },
    { id: 'que-rel', lemma: 'que', translation: 'that / which / who (relative pronoun)', hint: 'ke' },
    { id: 'quien-rel', lemma: 'quien', translation: 'who (relative pronoun)', hint: 'kyen' },
    { id: 'mi', lemma: 'mi', translation: 'my', hint: 'mi' },
    { id: 'abierto', lemma: 'abierto', translation: 'open (passive participle)', forms: ['abierta'], hint: 'abyerto' },
    { id: 'cerrado', lemma: 'cerrado', translation: 'closed (passive participle)', forms: ['cerrada'], hint: 'serrado' },
    { id: 'hecho', lemma: 'hecho', translation: 'done / made (passive participle)', forms: ['hecha'], hint: 'echo' },
    { id: 'dijo', lemma: 'dijo', translation: 'said (he/she said)', hint: 'diho' },
    { id: 'me', lemma: 'me', translation: 'me / to me', hint: 'me' },
    { id: 'te-pron', lemma: 'te', translation: 'you / to you (object pronoun)', hint: 'te' },
    { id: 'nos', lemma: 'nos', translation: 'us / to us', hint: 'nos' },
  ],
  patterns: [
    {
      id: 'que-es-esto',
      frame: '¿Qué es esto?',
      frameTranslation: 'What is this?',
      slots: [],
    },
    {
      id: 'esto-es-x',
      frame: 'Esto es ___',
      frameTranslation: 'This is ___',
      slots: [
        { vocabId: 'agua', form: 'agua', translation: 'water' },
        { vocabId: 'gato', form: 'un gato', translation: 'a cat' },
        { vocabId: 'casa', form: 'una casa', translation: 'a house' },
        { vocabId: 'libro', form: 'un libro', translation: 'a book' },
      ],
    },
    {
      id: 'quiero-x',
      frame: 'Quiero ___',
      frameTranslation: 'I want ___',
      slots: [
        { vocabId: 'te', form: 'té', translation: 'tea' },
        { vocabId: 'cafe', form: 'café', translation: 'coffee' },
        { vocabId: 'agua', form: 'agua', translation: 'water' },
        { vocabId: 'zumo', form: 'zumo', translation: 'juice' },
        { vocabId: 'pan', form: 'pan', translation: 'bread' },
        { vocabId: 'sopa', form: 'sopa', translation: 'soup' },
      ],
    },
    {
      id: 'tengo-x',
      frame: 'Tengo ___',
      frameTranslation: 'I have ___',
      slots: [
        { vocabId: 'gato', form: 'un gato', translation: 'a cat' },
        { vocabId: 'perro', form: 'un perro', translation: 'a dog' },
        { vocabId: 'libro', form: 'un libro', translation: 'a book' },
        { vocabId: 'telefono', form: 'un teléfono', translation: 'a phone' },
        { vocabId: 'dinero', form: 'dinero', translation: 'money' },
      ],
    },
    {
      id: 'amo-x',
      frame: 'Amo ___',
      frameTranslation: 'I love ___',
      slots: [
        { vocabId: 'madre', form: 'a mamá', translation: 'mom' },
        { vocabId: 'cafe', form: 'el café', translation: 'coffee' },
        { vocabId: 'espana', form: 'España', translation: 'Spain' },
      ],
    },
    {
      id: 'donde-esta-x',
      frame: '¿Dónde está ___?',
      frameTranslation: 'Where is ___?',
      slots: [
        { vocabId: 'bano', form: 'el baño', translation: 'the bathroom' },
        { vocabId: 'metro-es', form: 'el metro', translation: 'the metro' },
        { vocabId: 'estacion', form: 'la estación', translation: 'the station' },
        { vocabId: 'tienda', form: 'la tienda', translation: 'the shop' },
        { vocabId: 'restaurante', form: 'el restaurante', translation: 'the restaurant' },
      ],
    },
    {
      id: 'vivo-en-x',
      frame: 'Vivo en ___',
      frameTranslation: 'I live in ___',
      slots: [
        { vocabId: 'madrid', form: 'Madrid', translation: 'Madrid' },
        { vocabId: 'espana', form: 'España', translation: 'Spain' },
        { vocabId: 'ciudad', form: 'la ciudad', translation: 'the city' },
        { vocabId: 'casa', form: 'una casa', translation: 'a house' },
      ],
    },
    {
      id: 'es-muy-x',
      frame: 'Es muy ___',
      frameTranslation: 'It is very ___',
      slots: [
        { vocabId: 'bien', form: 'bueno', translation: 'good' },
        { vocabId: 'bonito', form: 'bonito', translation: 'beautiful' },
        { vocabId: 'rico', form: 'rico', translation: 'tasty' },
        { vocabId: 'grande', form: 'grande', translation: 'big' },
        { vocabId: 'caro', form: 'caro', translation: 'expensive' },
      ],
    },
    {
      id: 'cuanto-cuesta-x',
      frame: '¿Cuánto cuesta ___?',
      frameTranslation: 'How much does ___ cost?',
      slots: [
        { vocabId: 'pan', form: 'el pan', translation: 'the bread' },
        { vocabId: 'queso', form: 'el queso', translation: 'the cheese' },
        { vocabId: 'cafe', form: 'el café', translation: 'the coffee' },
        { vocabId: 'libro', form: 'el libro', translation: 'the book' },
        { vocabId: 'pescado', form: 'el pescado', translation: 'the fish' },
      ],
    },
    {
      id: 'voy-a-x',
      frame: 'Voy a ___',
      frameTranslation: 'I am going to ___',
      slots: [
        { vocabId: 'tienda', form: 'la tienda', translation: 'the shop' },
        { vocabId: 'escuela', form: 'la escuela', translation: 'school' },
        { vocabId: 'restaurante', form: 'el restaurante', translation: 'the restaurant' },
        { vocabId: 'parque', form: 'el parque', translation: 'the park' },
        { vocabId: 'casa', form: 'casa', translation: 'home' },
      ],
    },
    {
      id: 'tengo-feeling-x',
      frame: 'Tengo ___',
      frameTranslation: 'I am / I feel ___ (lit. I have)',
      slots: [
        { vocabId: 'frio', form: 'frío', translation: 'cold' },
        { vocabId: 'calor', form: 'calor', translation: 'hot' },
        { vocabId: 'hambre', form: 'hambre', translation: 'hungry' },
        { vocabId: 'sed', form: 'sed', translation: 'thirsty' },
      ],
    },
    {
      id: 'voy-a-infinitivo-x',
      frame: 'Mañana voy a ___',
      frameTranslation: 'Tomorrow I am going to ___',
      slots: [
        { vocabId: 'leer', form: 'leer', translation: 'read' },
        { vocabId: 'escribir', form: 'escribir', translation: 'write' },
        { vocabId: 'jugar', form: 'jugar', translation: 'play' },
        { vocabId: 'estudiar', form: 'estudiar', translation: 'study' },
      ],
    },
    {
      id: 'me-gusta-x',
      frame: 'Me gusta ___',
      frameTranslation: 'I like ___',
      slots: [
        { vocabId: 'te', form: 'el té', translation: 'tea' },
        { vocabId: 'cafe', form: 'el café', translation: 'coffee' },
        { vocabId: 'libro', form: 'el libro', translation: 'this book' },
        { vocabId: 'trabajo-n', form: 'el trabajo', translation: 'this job' },
      ],
    },
  ],
  units: [
    {
      id: 'u1',
      title: 'Survival patterns',
      description: 'Greetings, yes/no, and your first sentences',
      level: 'A1',
      skills: [
        {
          id: 'u1s1',
          title: 'Hello & thanks',
          icon: 'hand',
          lessons: [
            {
              id: 'u1s1l1',
              title: 'First words',
              vocabIds: ['hola', 'adios', 'si', 'no', 'gracias'],
              sentences: [
                { text: '¡Hola!', translation: 'Hello!', vocabIds: ['hola'] },
                { text: 'Sí, gracias.', translation: 'Yes, thank you.', vocabIds: ['si', 'gracias'] },
                { text: 'No, gracias.', translation: 'No, thank you.', vocabIds: ['no', 'gracias'] },
                { text: '¡Adiós!', translation: 'Goodbye!', vocabIds: ['adios'] },
              ],
            },
            {
              id: 'u1s1l2',
              title: 'Being polite',
              vocabIds: ['por-favor', 'perdon', 'buenos-dias'],
              sentences: [
                { text: '¡Buenos días!', translation: 'Good morning!', vocabIds: ['buenos-dias'] },
                { text: 'Perdón, por favor.', translation: 'Excuse me, please.', vocabIds: ['perdon', 'por-favor'] },
                { text: 'Gracias. — De nada.', translation: 'Thank you. — You are welcome.', vocabIds: ['gracias'] },
              ],
            },
          ],
        },
        {
          id: 'u1s2',
          title: 'This is…',
          icon: 'sparkles',
          lessons: [
            {
              id: 'u1s2l1',
              title: 'What is this?',
              vocabIds: ['esto', 'que', 'quien', 'yo', 'tu', 'es'],
              patternIds: ['que-es-esto', 'esto-es-x'],
              sentences: [
                { text: '¿Qué es esto?', translation: 'What is this?', vocabIds: ['que', 'es', 'esto'] },
                { text: 'Esto es una casa.', translation: 'This is a house.', vocabIds: ['esto', 'es', 'casa'] },
                { text: '¿Quién es?', translation: 'Who is it?', vocabIds: ['quien', 'es'] },
                { text: '¡Soy yo!', translation: 'It is me!', vocabIds: ['yo'] },
              ],
            },
            {
              id: 'u1s2l2',
              title: 'Good & bad',
              vocabIds: ['bien', 'mal', 'muy', 'usted'],
              sentences: [
                { text: '¡Muy bien!', translation: 'Very good!', vocabIds: ['muy', 'bien'] },
                { text: 'Esto está mal.', translation: 'This is bad.', vocabIds: ['esto', 'mal'] },
                { text: '¿Cómo está usted?', translation: 'How are you? (formal)', vocabIds: ['usted'] },
                { text: 'Bien, ¡gracias!', translation: 'Well, thanks!', vocabIds: ['bien', 'gracias'] },
              ],
            },
          ],
        },
      ],
    },
    {
      id: 'u2',
      title: 'I want / I have',
      description: 'Order food and talk about what you own',
      level: 'A1',
      skills: [
        {
          id: 'u2s1',
          title: 'I want…',
          icon: 'coffee',
          lessons: [
            {
              id: 'u2s1l1',
              title: 'Drinks',
              vocabIds: ['quiero', 'agua', 'te', 'cafe', 'zumo'],
              patternIds: ['quiero-x'],
              sentences: [
                { text: 'Quiero té.', translation: 'I want tea.', vocabIds: ['quiero', 'te'] },
                { text: 'Quiero café.', translation: 'I want coffee.', vocabIds: ['quiero', 'cafe'] },
                { text: 'Quiero agua, por favor.', translation: 'I want water, please.', vocabIds: ['quiero', 'agua', 'por-favor'] },
              ],
            },
            {
              id: 'u2s1l2',
              title: 'Food',
              vocabIds: ['pan', 'leche', 'queso', 'manzana', 'sopa', 'un'],
              sentences: [
                { text: 'Quiero pan y queso.', translation: 'I want bread and cheese.', vocabIds: ['quiero', 'pan', 'queso'] },
                { text: 'Esto es leche.', translation: 'This is milk.', vocabIds: ['esto', 'es', 'leche'] },
                { text: 'Una manzana, por favor.', translation: 'An apple, please.', vocabIds: ['un', 'manzana', 'por-favor'] },
                { text: 'La sopa está muy bien.', translation: 'The soup is very good.', vocabIds: ['sopa', 'muy', 'bien'] },
              ],
            },
          ],
        },
        {
          id: 'u2s2',
          title: 'I have…',
          icon: 'package',
          lessons: [
            {
              id: 'u2s2l1',
              title: 'My things',
              vocabIds: ['tengo', 'casa', 'gato', 'perro', 'libro'],
              patternIds: ['tengo-x'],
              sentences: [
                { text: 'Tengo un gato.', translation: 'I have a cat.', vocabIds: ['tengo', 'gato'] },
                { text: 'Tengo una casa.', translation: 'I have a house.', vocabIds: ['tengo', 'casa'] },
                { text: 'Tengo un perro y un gato.', translation: 'I have a dog and a cat.', vocabIds: ['tengo', 'perro', 'gato'] },
              ],
            },
            {
              id: 'u2s2l2',
              title: 'Phone & money',
              vocabIds: ['telefono', 'dinero'],
              sentences: [
                { text: 'Tengo un teléfono.', translation: 'I have a phone.', vocabIds: ['tengo', 'telefono'] },
                { text: 'Tengo dinero.', translation: 'I have money.', vocabIds: ['tengo', 'dinero'] },
                { text: '¿Es un teléfono? ¡Sí!', translation: 'Is it a phone? Yes!', vocabIds: ['es', 'telefono', 'si'] },
              ],
            },
          ],
        },
      ],
    },
    {
      id: 'u3',
      title: 'People & verbs',
      description: 'Family, friends, and your first verbs',
      level: 'A1',
      skills: [
        {
          id: 'u3s1',
          title: 'Family',
          icon: 'users',
          lessons: [
            {
              id: 'u3s1l1',
              title: 'Mom & dad',
              vocabIds: ['madre', 'padre', 'hermano', 'hermana', 'el', 'ella'],
              sentences: [
                { text: 'Esto es mamá y papá.', translation: 'This is mom and dad.', vocabIds: ['esto', 'madre', 'padre'] },
                { text: 'Él es hermano, ella es hermana.', translation: 'He is a brother, she is a sister.', vocabIds: ['el', 'hermano', 'ella', 'hermana'] },
                { text: 'Tengo un hermano.', translation: 'I have a brother.', vocabIds: ['tengo', 'hermano'] },
              ],
            },
            {
              id: 'u3s1l2',
              title: 'Friends & people',
              vocabIds: ['amigo', 'persona', 'nosotros', 'ellos', 'amo'],
              patternIds: ['amo-x'],
              sentences: [
                { text: 'Él es mi amigo.', translation: 'He is my friend.', vocabIds: ['el', 'amigo'] },
                { text: 'Amo a mamá.', translation: 'I love mom.', vocabIds: ['amo', 'madre'] },
                { text: 'Nosotros y ellos.', translation: 'We and they.', vocabIds: ['nosotros', 'ellos'] },
              ],
            },
          ],
        },
        {
          id: 'u3s2',
          title: 'First verbs',
          icon: 'message-circle',
          lessons: [
            {
              id: 'u3s2l1',
              title: 'Speak & understand',
              vocabIds: ['hablo', 'entiendo', 'se', 'espanol', 'ingles'],
              sentences: [
                { text: 'Hablo español.', translation: 'I speak Spanish.', vocabIds: ['hablo', 'espanol'] },
                { text: 'No entiendo.', translation: 'I do not understand.', vocabIds: ['entiendo'] },
                { text: '¿Hablas inglés?', translation: 'Do you speak English?', vocabIds: ['hablo', 'ingles'] },
                { text: 'Lo sé.', translation: 'I know.', vocabIds: ['se'] },
              ],
            },
            {
              id: 'u3s2l2',
              title: 'Live & work',
              vocabIds: ['vivo', 'trabajo-v'],
              sentences: [
                { text: 'Vivo aquí.', translation: 'I live here.', vocabIds: ['vivo', 'aqui'] },
                { text: 'Ella trabaja.', translation: 'She works.', vocabIds: ['ella', 'trabajo-v'] },
                { text: 'Trabajo en casa.', translation: 'I work at home.', vocabIds: ['trabajo-v', 'casa'] },
              ],
            },
          ],
        },
      ],
    },
    {
      id: 'u4',
      title: 'Places',
      description: 'Ask where things are and say where you live',
      level: 'A1',
      skills: [
        {
          id: 'u4s1',
          title: 'Where is…?',
          icon: 'map-pin',
          lessons: [
            {
              id: 'u4s1l1',
              title: 'Here & there',
              vocabIds: ['donde', 'aqui', 'alli', 'esta', 'bano', 'metro-es'],
              patternIds: ['donde-esta-x'],
              sentences: [
                { text: '¿Dónde está el baño?', translation: 'Where is the bathroom?', vocabIds: ['donde', 'esta', 'bano'] },
                { text: 'El metro está allí.', translation: 'The metro is there.', vocabIds: ['metro-es', 'esta', 'alli'] },
                { text: '¡Estoy aquí!', translation: 'I am here!', vocabIds: ['aqui'] },
              ],
            },
            {
              id: 'u4s1l2',
              title: 'Around town',
              vocabIds: ['tienda', 'estacion', 'restaurante', 'calle'],
              sentences: [
                { text: '¿Dónde está la tienda?', translation: 'Where is the shop?', vocabIds: ['donde', 'esta', 'tienda'] },
                { text: 'La estación está aquí, el restaurante allí.', translation: 'The station is here, the restaurant there.', vocabIds: ['estacion', 'aqui', 'restaurante', 'alli'] },
                { text: 'Esto es una calle.', translation: 'This is a street.', vocabIds: ['esto', 'es', 'calle'] },
              ],
            },
          ],
        },
        {
          id: 'u4s2',
          title: 'I live in…',
          icon: 'home',
          lessons: [
            {
              id: 'u4s2l1',
              title: 'City life',
              vocabIds: ['ciudad', 'madrid', 'espana', 'escuela', 'trabajo-n'],
              patternIds: ['vivo-en-x'],
              sentences: [
                { text: 'Vivo en Madrid.', translation: 'I live in Madrid.', vocabIds: ['vivo', 'madrid'] },
                { text: 'Madrid es una ciudad en España.', translation: 'Madrid is a city in Spain.', vocabIds: ['madrid', 'es', 'ciudad', 'espana'] },
                { text: 'La escuela está allí.', translation: 'The school is there.', vocabIds: ['escuela', 'esta', 'alli'] },
              ],
            },
          ],
        },
      ],
    },
    {
      id: 'u5',
      title: 'Numbers & time',
      description: 'Count to ten and talk about your day',
      level: 'A1',
      skills: [
        {
          id: 'u5s1',
          title: 'One to ten',
          icon: 'hash',
          lessons: [
            {
              id: 'u5s1l1',
              title: '1–5',
              vocabIds: ['uno', 'dos', 'tres', 'cuatro', 'cinco'],
              sentences: [
                { text: 'Uno, dos, tres.', translation: 'One, two, three.', vocabIds: ['uno', 'dos', 'tres'] },
                { text: 'Cuatro y cinco.', translation: 'Four and five.', vocabIds: ['cuatro', 'cinco'] },
                { text: 'Tengo dos gatos.', translation: 'I have two cats.', vocabIds: ['tengo', 'dos', 'gato'] },
              ],
            },
            {
              id: 'u5s1l2',
              title: '6–10',
              vocabIds: ['seis', 'siete', 'ocho', 'nueve', 'diez'],
              sentences: [
                { text: 'Seis, siete, ocho.', translation: 'Six, seven, eight.', vocabIds: ['seis', 'siete', 'ocho'] },
                { text: 'Nueve y diez.', translation: 'Nine and ten.', vocabIds: ['nueve', 'diez'] },
              ],
            },
          ],
        },
        {
          id: 'u5s2',
          title: 'My day',
          icon: 'clock',
          lessons: [
            {
              id: 'u5s2l1',
              title: 'Times of day',
              vocabIds: ['manana-time', 'dia', 'tarde', 'noche', 'hora'],
              sentences: [
                { text: 'Mañana, día, tarde, noche.', translation: 'Morning, day, afternoon, night.', vocabIds: ['manana-time', 'dia', 'tarde', 'noche'] },
                { text: '¿Qué hora es?', translation: 'What time is it?', vocabIds: ['que', 'hora', 'es'] },
              ],
            },
            {
              id: 'u5s2l2',
              title: 'Today & now',
              vocabIds: ['hoy', 'ahora', 'cuando', 'cuanto'],
              sentences: [
                { text: '¿Cuándo? ¿Hoy o mañana?', translation: 'When? Today or tomorrow?', vocabIds: ['cuando', 'hoy', 'manana-time'] },
                { text: '¡Ahora!', translation: 'Now!', vocabIds: ['ahora'] },
                { text: '¿Cuánto es esto?', translation: 'How much is this?', vocabIds: ['cuanto', 'es', 'esto'] },
              ],
            },
          ],
        },
      ],
    },
    {
      id: 'u6',
      title: 'Describing things',
      description: 'Colors and your first adjectives',
      level: 'A1',
      skills: [
        {
          id: 'u6s1',
          title: 'Colors',
          icon: 'sparkles',
          lessons: [
            {
              id: 'u6s1l1',
              title: 'Red, blue, green',
              vocabIds: ['rojo', 'azul', 'verde'],
              sentences: [
                { text: 'Esto es una casa roja.', translation: 'This is a red house.', vocabIds: ['esto', 'es', 'casa', 'rojo'] },
                { text: '¿El gato es azul? ¡No!', translation: 'Is the cat blue? No!', vocabIds: ['gato', 'es', 'azul', 'no'] },
                { text: 'El parque es verde.', translation: 'The park is green.', vocabIds: ['parque', 'es', 'verde'] },
              ],
            },
            {
              id: 'u6s1l2',
              title: 'Yellow, black, white',
              vocabIds: ['amarillo', 'negro', 'blanco'],
              sentences: [
                { text: 'El sol es amarillo.', translation: 'The sun is yellow.', vocabIds: ['sol', 'es', 'amarillo'] },
                { text: 'Un gato negro y un perro blanco.', translation: 'A black cat and a white dog.', vocabIds: ['gato', 'negro', 'perro', 'blanco'] },
                { text: 'La nieve es blanca.', translation: 'Snow is white.', vocabIds: ['nieve', 'es', 'blanco'] },
              ],
            },
          ],
        },
        {
          id: 'u6s2',
          title: 'Big & small',
          icon: 'package',
          lessons: [
            {
              id: 'u6s2l1',
              title: 'Size & age',
              vocabIds: ['grande', 'pequeno', 'nuevo', 'viejo'],
              sentences: [
                { text: 'Es una ciudad grande.', translation: 'It is a big city.', vocabIds: ['es', 'ciudad', 'grande'] },
                { text: 'Un gato pequeño, un perro grande.', translation: 'A small cat, a big dog.', vocabIds: ['gato', 'pequeno', 'perro', 'grande'] },
                { text: 'Tengo un teléfono nuevo.', translation: 'I have a new phone.', vocabIds: ['tengo', 'telefono', 'nuevo'] },
                { text: 'Es una casa vieja.', translation: 'It is an old house.', vocabIds: ['es', 'casa', 'viejo'] },
              ],
            },
            {
              id: 'u6s2l2',
              title: 'Beautiful & tasty',
              vocabIds: ['bonito', 'rico'],
              patternIds: ['es-muy-x'],
              sentences: [
                { text: 'Madrid es una ciudad bonita.', translation: 'Madrid is a beautiful city.', vocabIds: ['madrid', 'es', 'ciudad', 'bonito'] },
                { text: '¡La sopa está muy rica!', translation: 'The soup is very tasty!', vocabIds: ['sopa', 'muy', 'rico'] },
                { text: 'Es muy bonito.', translation: 'It is very beautiful.', vocabIds: ['es', 'muy', 'bonito'] },
              ],
            },
          ],
        },
      ],
    },
    {
      id: 'u7',
      title: 'Days & questions',
      description: 'The week and how to ask about anything',
      level: 'A1',
      skills: [
        {
          id: 'u7s1',
          title: 'Days of the week',
          icon: 'clock',
          lessons: [
            {
              id: 'u7s1l1',
              title: 'Monday to Thursday',
              vocabIds: ['lunes', 'martes', 'miercoles', 'jueves'],
              sentences: [
                { text: 'Hoy es lunes.', translation: 'Today is Monday.', vocabIds: ['hoy', 'es', 'lunes'] },
                { text: 'Mañana es martes.', translation: 'Tomorrow is Tuesday.', vocabIds: ['manana-time', 'es', 'martes'] },
                { text: '¿Miércoles o jueves?', translation: 'Wednesday or Thursday?', vocabIds: ['miercoles', 'jueves'] },
              ],
            },
            {
              id: 'u7s1l2',
              title: 'The weekend',
              vocabIds: ['viernes', 'sabado', 'domingo', 'semana'],
              sentences: [
                { text: '¡Amo el viernes!', translation: 'I love Friday!', vocabIds: ['amo', 'viernes'] },
                { text: 'Sábado y domingo.', translation: 'Saturday and Sunday.', vocabIds: ['sabado', 'domingo'] },
                { text: 'Una semana es siete días.', translation: 'A week is seven days.', vocabIds: ['semana', 'es', 'siete', 'dia'] },
              ],
            },
          ],
        },
        {
          id: 'u7s2',
          title: 'Asking questions',
          icon: 'message-circle',
          lessons: [
            {
              id: 'u7s2l1',
              title: 'How, why, which',
              vocabIds: ['como', 'por-que', 'cual'],
              sentences: [
                { text: '¿Cómo estás?', translation: 'How are you?', vocabIds: ['como'] },
                { text: '¿Por qué no?', translation: 'Why not?', vocabIds: ['por-que', 'no'] },
                { text: '¿Cuál es tu color?', translation: 'Which is your color?', vocabIds: ['cual', 'es'] },
                { text: '¿Qué día es hoy?', translation: 'What day is it today?', vocabIds: ['que', 'dia', 'es', 'hoy'] },
              ],
            },
          ],
        },
      ],
    },
    {
      id: 'u8',
      title: 'Food & shopping',
      description: 'Buy food and ask prices like a local',
      level: 'A1',
      skills: [
        {
          id: 'u8s1',
          title: 'More food',
          icon: 'coffee',
          lessons: [
            {
              id: 'u8s1l1',
              title: 'Meat & fish',
              vocabIds: ['carne', 'pescado', 'huevo', 'comer'],
              sentences: [
                { text: 'Como carne y pescado.', translation: 'I eat meat and fish.', vocabIds: ['comer', 'carne', 'pescado'] },
                { text: 'Esto es un huevo.', translation: 'This is an egg.', vocabIds: ['esto', 'es', 'huevo'] },
                { text: '¿Comes pescado?', translation: 'Do you eat fish?', vocabIds: ['comer', 'pescado'] },
              ],
            },
            {
              id: 'u8s1l2',
              title: 'Fruit & veg',
              vocabIds: ['fruta', 'verduras', 'azucar', 'sal'],
              sentences: [
                { text: 'La fruta y las verduras son buenas.', translation: 'Fruit and vegetables are good.', vocabIds: ['fruta', 'verduras', 'bien'] },
                { text: '¿Azúcar o sal?', translation: 'Sugar or salt?', vocabIds: ['azucar', 'sal'] },
                { text: 'Quiero fruta.', translation: 'I want fruit.', vocabIds: ['quiero', 'fruta'] },
              ],
            },
          ],
        },
        {
          id: 'u8s2',
          title: 'How much?',
          icon: 'hash',
          lessons: [
            {
              id: 'u8s2l1',
              title: 'Prices',
              vocabIds: ['comprar', 'cuesta', 'caro', 'barato'],
              patternIds: ['cuanto-cuesta-x'],
              sentences: [
                { text: '¿Cuánto cuesta el pan?', translation: 'How much does the bread cost?', vocabIds: ['cuanto', 'cuesta', 'pan'] },
                { text: '¡Es muy caro!', translation: 'It is very expensive!', vocabIds: ['es', 'muy', 'caro'] },
                { text: '¡Barato! Quiero comprar.', translation: 'Cheap! I want to buy it.', vocabIds: ['barato', 'quiero', 'comprar'] },
              ],
            },
          ],
        },
      ],
    },
    {
      id: 'u9',
      title: 'Action verbs',
      description: 'Go, eat, drink, see, do, think, sleep',
      level: 'A1',
      skills: [
        {
          id: 'u9s1',
          title: 'Going places',
          icon: 'map-pin',
          lessons: [
            {
              id: 'u9s1l1',
              title: 'I am going…',
              vocabIds: ['ir', 'parque'],
              patternIds: ['voy-a-x'],
              sentences: [
                { text: 'Voy a la tienda.', translation: 'I am going to the shop.', vocabIds: ['ir', 'tienda'] },
                { text: 'Vamos al parque.', translation: 'We are going to the park.', vocabIds: ['ir', 'parque'] },
                { text: '¿Adónde vas?', translation: 'Where are you going?', vocabIds: ['ir'] },
              ],
            },
            {
              id: 'u9s1l2',
              title: 'Eat & drink',
              vocabIds: ['beber'],
              sentences: [
                { text: 'Bebo café.', translation: 'I drink coffee.', vocabIds: ['beber', 'cafe'] },
                { text: 'Él bebe té, ella bebe zumo.', translation: 'He drinks tea, she drinks juice.', vocabIds: ['el', 'beber', 'te', 'ella', 'zumo'] },
                { text: 'Como y bebo.', translation: 'I eat and drink.', vocabIds: ['comer', 'beber'] },
              ],
            },
          ],
        },
        {
          id: 'u9s2',
          title: 'Think & do',
          icon: 'sparkles',
          lessons: [
            {
              id: 'u9s2l1',
              title: 'See, do, think',
              vocabIds: ['ver-verb', 'hacer', 'pensar'],
              sentences: [
                { text: 'Veo un gato.', translation: 'I see a cat.', vocabIds: ['ver-verb', 'gato'] },
                { text: '¿Qué haces?', translation: 'What are you doing?', vocabIds: ['que', 'hacer'] },
                { text: 'Pienso que es bueno.', translation: 'I think it is good.', vocabIds: ['pensar', 'es', 'bien'] },
              ],
            },
            {
              id: 'u9s2l2',
              title: 'Sleep',
              vocabIds: ['dormir'],
              sentences: [
                { text: 'Duermo.', translation: 'I am sleeping.', vocabIds: ['dormir'] },
                { text: 'El gato duerme en casa.', translation: 'The cat sleeps at home.', vocabIds: ['gato', 'dormir', 'casa'] },
                { text: 'De noche duermo, de mañana trabajo.', translation: 'At night I sleep, in the morning I work.', vocabIds: ['noche', 'dormir', 'manana-time', 'trabajo-v'] },
              ],
            },
          ],
        },
      ],
    },
    {
      id: 'u10',
      title: 'Weather & feelings',
      description: 'Talk about the weather and how you feel',
      level: 'A1',
      skills: [
        {
          id: 'u10s1',
          title: 'Weather',
          icon: 'home',
          lessons: [
            {
              id: 'u10s1l1',
              title: 'Hot & cold',
              vocabIds: ['tiempo', 'frio', 'calor', 'hambre', 'sed'],
              patternIds: ['tengo-feeling-x'],
              sentences: [
                { text: '¿Qué tiempo hace hoy?', translation: 'What is the weather today?', vocabIds: ['que', 'tiempo', 'hoy'] },
                { text: '¡Tengo frío!', translation: 'I am cold!', vocabIds: ['tengo', 'frio'] },
                { text: 'Tengo hambre y sed.', translation: 'I am hungry and thirsty.', vocabIds: ['tengo', 'hambre', 'sed'] },
              ],
            },
            {
              id: 'u10s1l2',
              title: 'Rain & snow',
              vocabIds: ['lluvia', 'nieve', 'sol'],
              sentences: [
                { text: '¿Lluvia o nieve?', translation: 'Rain or snow?', vocabIds: ['lluvia', 'nieve'] },
                { text: 'Amo el sol.', translation: 'I love the sun.', vocabIds: ['amo', 'sol'] },
                { text: 'Hoy hace sol.', translation: 'It is sunny today.', vocabIds: ['hoy', 'sol'] },
              ],
            },
          ],
        },
        {
          id: 'u10s2',
          title: 'Feelings',
          icon: 'users',
          lessons: [
            {
              id: 'u10s2l1',
              title: 'Tired & happy',
              vocabIds: ['cansado', 'feliz'],
              sentences: [
                { text: 'Estoy cansado. Voy a dormir.', translation: 'I am tired. I am going to sleep.', vocabIds: ['cansado', 'ir', 'dormir'] },
                { text: '¡Estoy muy feliz!', translation: 'I am very happy!', vocabIds: ['muy', 'feliz'] },
                { text: 'Hoy estoy bien.', translation: 'Today I feel good.', vocabIds: ['hoy', 'bien'] },
              ],
            },
          ],
        },
      ],
    },
    {
      id: 'u11',
      title: 'Yesterday & tomorrow',
      description: 'Past tense, reflexive verbs, gustar, and plans for the future',
      level: 'A2',
      skills: [
        {
          id: 'u11s1',
          title: 'Past tense',
          icon: 'clock',
          lessons: [
            {
              id: 'u11s1l1',
              title: 'Yesterday',
              vocabIds: ['ayer', 'estar', 'leer', 'escribir'],
              sentences: [
                { text: 'Ayer leí un libro.', translation: 'Yesterday I read a book.', vocabIds: ['ayer', 'leer', 'libro'] },
                { text: 'Ayer estuvo frío.', translation: 'Yesterday it was cold.', vocabIds: ['ayer', 'estar', 'frio'] },
                { text: 'Escribí ayer.', translation: 'I wrote yesterday.', vocabIds: ['escribir', 'ayer'] },
                { text: '¿Estuviste en casa ayer?', translation: 'Were you home yesterday?', vocabIds: ['estar', 'casa', 'ayer'] },
              ],
            },
            {
              id: 'u11s1l2',
              title: 'What we did',
              vocabIds: ['escuchar', 'jugar', 'pelicula', 'musica'],
              sentences: [
                { text: 'Vi una película.', translation: 'I watched a movie.', vocabIds: ['ver-verb', 'pelicula'] },
                { text: '¿Escuchas música?', translation: 'Are you listening to music?', vocabIds: ['escuchar', 'musica'] },
                { text: 'Jugamos en el parque.', translation: 'We play in the park.', vocabIds: ['jugar', 'parque'] },
                { text: 'Juego y escucho música.', translation: 'I play and listen to music.', vocabIds: ['jugar', 'escuchar', 'musica'] },
              ],
            },
          ],
        },
        {
          id: 'u11s2',
          title: 'Reflexive verbs & routines',
          icon: 'home',
          lessons: [
            {
              id: 'u11s2l1',
              title: 'Morning routine',
              vocabIds: ['levantarse', 'ducharse', 'vestirse'],
              sentences: [
                { text: 'Me levanto a las siete.', translation: 'I get up at seven.', vocabIds: ['levantarse', 'siete'] },
                { text: 'Me ducho por la mañana.', translation: 'I shower in the morning.', vocabIds: ['ducharse', 'manana-time'] },
                { text: '¿Te vistes ahora?', translation: 'Are you getting dressed now?', vocabIds: ['vestirse', 'ahora'] },
                { text: 'Me levanto, me ducho y me visto.', translation: 'I get up, shower, and get dressed.', vocabIds: ['levantarse', 'ducharse', 'vestirse'] },
              ],
            },
            {
              id: 'u11s2l2',
              title: 'Around the house',
              vocabIds: ['acostarse', 'apartamento', 'habitacion', 'cocina'],
              sentences: [
                { text: 'Me acuesto a las diez.', translation: 'I go to bed at ten.', vocabIds: ['acostarse', 'diez'] },
                { text: 'Tengo un apartamento pequeño.', translation: 'I have a small apartment.', vocabIds: ['tengo', 'apartamento', 'pequeno'] },
                { text: 'La habitación es grande.', translation: 'The bedroom is big.', vocabIds: ['habitacion', 'es', 'grande'] },
                { text: 'La cocina está aquí.', translation: 'The kitchen is here.', vocabIds: ['cocina', 'esta', 'aqui'] },
              ],
            },
          ],
        },
        {
          id: 'u11s3',
          title: 'Future plans',
          icon: 'sparkles',
          lessons: [
            {
              id: 'u11s3l1',
              title: 'Tomorrow',
              vocabIds: ['entonces', 'necesito'],
              patternIds: ['voy-a-infinitivo-x'],
              sentences: [
                { text: 'Mañana voy a leer.', translation: 'Tomorrow I am going to read.', vocabIds: ['manana-time', 'ir', 'leer'] },
                { text: 'Necesito trabajar, entonces voy a dormir.', translation: 'I need to work, so I am going to sleep.', vocabIds: ['necesito', 'trabajo-n', 'entonces', 'ir', 'dormir'] },
                { text: '¿Qué vas a hacer mañana?', translation: 'What are you going to do tomorrow?', vocabIds: ['que', 'ir', 'hacer', 'manana-time'] },
                { text: 'Mañana va a estar bien.', translation: 'Tomorrow is going to be good.', vocabIds: ['manana-time', 'estar', 'bien'] },
              ],
            },
            {
              id: 'u11s3l2',
              title: 'Commands',
              vocabIds: ['ve', 'mira', 'di'],
              sentences: [
                { text: 'Necesito ir.', translation: 'I need to go.', vocabIds: ['necesito', 'ir'] },
                { text: '¡Ve a casa!', translation: 'Go home!', vocabIds: ['ve', 'casa'] },
                { text: '¡Mira! Es un gato.', translation: 'Look! It is a cat.', vocabIds: ['mira', 'es', 'gato'] },
                { text: 'Di, por favor, ¿dónde está el metro?', translation: 'Please tell me, where is the metro?', vocabIds: ['di', 'por-favor', 'donde', 'esta', 'metro-es'] },
              ],
            },
          ],
        },
        {
          id: 'u11s4',
          title: 'Likes & pronouns',
          icon: 'message-circle',
          lessons: [
            {
              id: 'u11s4l1',
              title: 'I like',
              vocabIds: ['gustar', 'mas', 'menos'],
              patternIds: ['me-gusta-x'],
              sentences: [
                { text: 'Me gusta el té.', translation: 'I like tea.', vocabIds: ['gustar', 'te'] },
                { text: '¿Te gusta el café?', translation: 'Do you like coffee?', vocabIds: ['gustar', 'cafe'] },
                { text: 'Me gusta más el café que el té.', translation: 'I like coffee more than tea.', vocabIds: ['gustar', 'mas', 'cafe', 'que', 'te'] },
                { text: 'Me gusta menos el frío.', translation: 'I like the cold less.', vocabIds: ['gustar', 'menos', 'frio'] },
              ],
            },
            {
              id: 'u11s4l2',
              title: 'Pronouns',
              vocabIds: ['lo', 'le'],
              sentences: [
                { text: 'Lo tengo.', translation: 'I have it.', vocabIds: ['lo', 'tengo'] },
                { text: 'Le hablo.', translation: 'I speak to him/her.', vocabIds: ['le', 'hablo'] },
                { text: '¿Lo ves?', translation: 'Do you see it?', vocabIds: ['lo', 'ver-verb'] },
                { text: 'Le gusta el libro.', translation: 'He/she likes the book.', vocabIds: ['le', 'gustar', 'libro'] },
              ],
            },
          ],
        },
        {
          id: 'u11s5',
          title: 'Health, work & study',
          icon: 'users',
          lessons: [
            {
              id: 'u11s5l1',
              title: 'Health',
              vocabIds: ['enfermo', 'dolor', 'medico'],
              sentences: [
                { text: 'Estoy enfermo.', translation: 'I am sick.', vocabIds: ['enfermo'] },
                { text: 'Tengo dolor.', translation: 'I have pain.', vocabIds: ['tengo', 'dolor'] },
                { text: 'El médico está aquí.', translation: 'The doctor is here.', vocabIds: ['medico', 'esta', 'aqui'] },
                { text: 'Ella es médica.', translation: 'She is a doctor.', vocabIds: ['ella', 'medico'] },
              ],
            },
            {
              id: 'u11s5l2',
              title: 'Work & study',
              vocabIds: ['estudiar', 'oficina', 'universidad'],
              sentences: [
                { text: 'Estudio en la universidad.', translation: 'I study at the university.', vocabIds: ['estudiar', 'universidad'] },
                { text: 'Trabajo en una oficina.', translation: 'I work in an office.', vocabIds: ['trabajo-n', 'oficina'] },
                { text: '¿Qué estudias?', translation: 'What do you study?', vocabIds: ['que', 'estudiar'] },
                { text: 'Mi padre trabaja en una oficina grande.', translation: 'My father works in a big office.', vocabIds: ['padre', 'trabajo-n', 'oficina', 'grande'] },
              ],
            },
          ],
        },
      ],
    },
    {
      id: 'u12',
      title: 'Mastering tenses',
      description: 'Present subjunctive, perfect tenses, and por vs. para',
      level: 'B1',
      skills: [
        {
          id: 'u12s1',
          title: 'Present subjunctive',
          icon: 'sparkles',
          lessons: [
            {
              id: 'u12s1l1',
              title: 'Hoping & wishing',
              vocabIds: ['espero', 'ojala', 'venga', 'tenga'],
              sentences: [
                { text: 'Espero que tengas tiempo.', translation: 'I hope you have time.', vocabIds: ['espero', 'tenga', 'tiempo'] },
                { text: 'Ojalá tengas dinero.', translation: 'I wish you have money.', vocabIds: ['ojala', 'tenga', 'dinero'] },
                { text: 'Espero que estés bien.', translation: 'I hope you are well.', vocabIds: ['espero', 'estar', 'bien'] },
                { text: 'Ojalá vengas mañana.', translation: 'I wish you come tomorrow.', vocabIds: ['ojala', 'venga', 'manana-time'] },
              ],
            },
            {
              id: 'u12s1l2',
              title: 'Maybe & possibility',
              vocabIds: ['quizas'],
              sentences: [
                { text: 'Quizás venga mañana.', translation: 'Maybe he will come tomorrow.', vocabIds: ['quizas', 'venga', 'manana-time'] },
                { text: 'Quizás tenga tiempo.', translation: 'Maybe she has time.', vocabIds: ['quizas', 'tenga', 'tiempo'] },
                { text: 'Espero que venga.', translation: 'I hope he comes.', vocabIds: ['espero', 'venga'] },
                { text: 'Quizás esté en casa.', translation: 'Maybe she is at home.', vocabIds: ['quizas', 'estar', 'casa'] },
              ],
            },
          ],
        },
        {
          id: 'u12s2',
          title: 'Perfect tenses',
          icon: 'clock',
          lessons: [
            {
              id: 'u12s2l1',
              title: 'I have done',
              vocabIds: ['he', 'comido', 'hablado'],
              sentences: [
                { text: 'He comido.', translation: 'I have eaten.', vocabIds: ['he', 'comido'] },
                { text: 'He hablado español.', translation: 'I have spoken Spanish.', vocabIds: ['he', 'hablado', 'espanol'] },
                { text: '¿Has comido?', translation: 'Have you eaten?', vocabIds: ['he', 'comido'] },
                { text: 'Ella ha hablado con el médico.', translation: 'She has spoken with the doctor.', vocabIds: ['ella', 'he', 'hablado', 'medico'] },
              ],
            },
            {
              id: 'u12s2l2',
              title: 'I have lived',
              vocabIds: ['vivido'],
              sentences: [
                { text: 'He vivido en Madrid.', translation: 'I have lived in Madrid.', vocabIds: ['he', 'vivido', 'madrid'] },
                { text: '¿Has vivido aquí?', translation: 'Have you lived here?', vocabIds: ['he', 'vivido', 'aqui'] },
                { text: 'Hemos vivido en España.', translation: 'We have lived in Spain.', vocabIds: ['he', 'vivido', 'espana'] },
                { text: 'Ha vivido aquí.', translation: 'She has lived here.', vocabIds: ['he', 'vivido', 'aqui'] },
              ],
            },
          ],
        },
        {
          id: 'u12s3',
          title: 'Por vs. para',
          icon: 'map-pin',
          lessons: [
            {
              id: 'u12s3l1',
              title: 'Para — purpose & destination',
              vocabIds: ['para'],
              sentences: [
                { text: 'Esto es para ti.', translation: 'This is for you.', vocabIds: ['esto', 'para', 'tu'] },
                { text: 'Voy para Madrid.', translation: 'I am heading to Madrid.', vocabIds: ['ir', 'para', 'madrid'] },
                { text: 'Trabajo para vivir.', translation: 'I work in order to live.', vocabIds: ['trabajo-v', 'para', 'vivo'] },
                { text: 'Para mí, es bueno.', translation: 'For me, it is good.', vocabIds: ['para', 'yo', 'bien'] },
              ],
            },
            {
              id: 'u12s3l2',
              title: 'Por — reason & exchange',
              vocabIds: ['por'],
              sentences: [
                { text: 'Gracias por el café.', translation: 'Thanks for the coffee.', vocabIds: ['gracias', 'por', 'cafe'] },
                { text: 'Voy por la calle.', translation: 'I walk through the street.', vocabIds: ['ir', 'por', 'calle'] },
                { text: 'Trabajo por dinero.', translation: 'I work for money.', vocabIds: ['trabajo-v', 'por', 'dinero'] },
                { text: 'Por la mañana, trabajo.', translation: 'In the morning, I work.', vocabIds: ['por', 'manana-time', 'trabajo-v'] },
              ],
            },
          ],
        },
      ],
    },
    {
      id: 'u13',
      title: 'Real fluency',
      description: 'Conditional mood, relative clauses, passive voice, and reported speech',
      level: 'B2',
      skills: [
        {
          id: 'u13s1',
          title: 'Conditional mood',
          icon: 'sparkles',
          lessons: [
            {
              id: 'u13s1l1',
              title: 'Would',
              vocabIds: ['seria', 'tendria'],
              sentences: [
                { text: 'Sería bueno.', translation: 'It would be good.', vocabIds: ['seria', 'bien'] },
                { text: 'Tendría tiempo.', translation: 'I would have time.', vocabIds: ['tendria', 'tiempo'] },
                { text: 'Sería un médico.', translation: 'He would be a doctor.', vocabIds: ['seria', 'medico'] },
                { text: 'Si tengo dinero, sería feliz.', translation: 'If I have money, I would be happy.', vocabIds: ['si-if', 'tengo', 'dinero', 'seria', 'feliz'] },
              ],
            },
            {
              id: 'u13s1l2',
              title: 'I would like',
              vocabIds: ['gustaria', 'si-if'],
              sentences: [
                { text: 'Me gustaría un café.', translation: 'I would like a coffee.', vocabIds: ['gustar', 'gustaria', 'cafe'] },
                { text: 'Si tengo tiempo, me gustaría leer.', translation: 'If I have time, I would like to read.', vocabIds: ['si-if', 'tengo', 'tiempo', 'gustaria', 'leer'] },
                { text: '¿Te gustaría ir al parque?', translation: 'Would you like to go to the park?', vocabIds: ['gustaria', 'ir', 'parque'] },
                { text: 'Me gustaría vivir en Madrid.', translation: 'I would like to live in Madrid.', vocabIds: ['gustaria', 'vivo', 'madrid'] },
              ],
            },
          ],
        },
        {
          id: 'u13s2',
          title: 'Relative clauses',
          icon: 'users',
          lessons: [
            {
              id: 'u13s2l1',
              title: 'The person who...',
              vocabIds: ['que-rel'],
              sentences: [
                { text: 'La persona que trabaja aquí es médica.', translation: 'The person who works here is a doctor.', vocabIds: ['persona', 'que-rel', 'trabajo-v', 'aqui', 'medico'] },
                { text: 'El libro que leo es bueno.', translation: 'The book that I am reading is good.', vocabIds: ['libro', 'que-rel', 'leer', 'bien'] },
                { text: 'La casa que tengo es grande.', translation: 'The house that I have is big.', vocabIds: ['casa', 'que-rel', 'tengo', 'grande'] },
                { text: 'El amigo que vive aquí es bueno.', translation: 'The friend who lives here is good.', vocabIds: ['amigo', 'que-rel', 'vivo', 'aqui', 'bien'] },
              ],
            },
            {
              id: 'u13s2l2',
              title: 'The one who...',
              vocabIds: ['quien-rel', 'mi'],
              sentences: [
                { text: 'Quien trabaja, sabe.', translation: 'Whoever works, knows.', vocabIds: ['quien-rel', 'trabajo-v', 'se'] },
                { text: 'El médico, quien vive aquí, es bueno.', translation: 'The doctor, who lives here, is good.', vocabIds: ['medico', 'quien-rel', 'vivo', 'aqui', 'bien'] },
                { text: 'Mi amiga, quien es médica, trabaja aquí.', translation: 'My friend, who is a doctor, works here.', vocabIds: ['mi', 'quien-rel', 'medico', 'trabajo-v', 'aqui'] },
                { text: 'La persona, quien trabaja aquí, es feliz.', translation: 'The person, who works here, is happy.', vocabIds: ['persona', 'quien-rel', 'trabajo-v', 'aqui', 'feliz'] },
              ],
            },
          ],
        },
        {
          id: 'u13s3',
          title: 'Passive voice',
          icon: 'home',
          lessons: [
            {
              id: 'u13s3l1',
              title: 'Open & closed',
              vocabIds: ['abierto', 'cerrado'],
              sentences: [
                { text: 'La tienda está abierta.', translation: 'The shop is open.', vocabIds: ['tienda', 'abierto'] },
                { text: 'La escuela está cerrada.', translation: 'The school is closed.', vocabIds: ['escuela', 'cerrado'] },
                { text: 'Hoy la tienda está cerrada.', translation: 'Today the shop is closed.', vocabIds: ['hoy', 'tienda', 'cerrado'] },
                { text: 'El parque está abierto.', translation: 'The park is open.', vocabIds: ['parque', 'abierto'] },
              ],
            },
            {
              id: 'u13s3l2',
              title: 'It is done',
              vocabIds: ['hecho'],
              sentences: [
                { text: 'Esto está hecho.', translation: 'This is done.', vocabIds: ['esto', 'hecho'] },
                { text: 'El trabajo está bien hecho.', translation: 'The work is well done.', vocabIds: ['trabajo-n', 'bien', 'hecho'] },
                { text: 'La casa está mal hecha.', translation: 'The house is badly made.', vocabIds: ['casa', 'mal', 'hecho'] },
                { text: 'Esto está mal hecho.', translation: 'This is badly done.', vocabIds: ['esto', 'mal', 'hecho'] },
              ],
            },
          ],
        },
        {
          id: 'u13s4',
          title: 'Reported speech',
          icon: 'message-circle',
          lessons: [
            {
              id: 'u13s4l1',
              title: 'He/she said that...',
              vocabIds: ['dijo'],
              sentences: [
                { text: 'Ella dijo que está bien.', translation: 'She said that she is well.', vocabIds: ['ella', 'dijo', 'que-rel', 'estar', 'bien'] },
                { text: 'Él dijo que tiene tiempo.', translation: 'He said that he has time.', vocabIds: ['el', 'dijo', 'que-rel', 'tengo', 'tiempo'] },
                { text: 'Mi amigo dijo que vive aquí.', translation: 'My friend said that he lives here.', vocabIds: ['mi', 'amigo', 'dijo', 'que-rel', 'vivo', 'aqui'] },
                { text: 'El médico dijo que el trabajo está hecho.', translation: 'The doctor said that the work is done.', vocabIds: ['medico', 'dijo', 'que-rel', 'trabajo-n', 'hecho'] },
              ],
            },
            {
              id: 'u13s4l2',
              title: 'Told me, you, us',
              vocabIds: ['me', 'te-pron', 'nos'],
              sentences: [
                { text: 'Me dijo que va a la tienda.', translation: 'He told me that he is going to the shop.', vocabIds: ['me', 'dijo', 'ir', 'tienda'] },
                { text: 'Me dijo que es feliz.', translation: 'She told me that she is happy.', vocabIds: ['me', 'dijo', 'feliz'] },
                { text: 'Te dijo que tiene hambre.', translation: 'He told you that he is hungry.', vocabIds: ['te-pron', 'dijo', 'tengo', 'hambre'] },
                { text: 'Nos dijo que trabaja aquí.', translation: 'She told us that she works here.', vocabIds: ['nos', 'dijo', 'trabajo-v', 'aqui'] },
              ],
            },
          ],
        },
      ],
    },
  ],
}
