import type { Course } from '../types'

export const esCourse: Course = {
  id: 'es',
  name: 'Spanish',
  flag: '🇪🇸',
  ttsLang: 'es-ES',
  vocab: [
    // Unit 1 — survival
    { id: 'hola', lemma: 'hola', translation: 'hello' },
    { id: 'adios', lemma: 'adiós', translation: 'goodbye' },
    { id: 'si', lemma: 'sí', translation: 'yes' },
    { id: 'no', lemma: 'no', translation: 'no' },
    { id: 'gracias', lemma: 'gracias', translation: 'thank you' },
    { id: 'por-favor', lemma: 'por favor', translation: 'please' },
    { id: 'perdon', lemma: 'perdón', translation: 'excuse me / sorry' },
    { id: 'bien', lemma: 'bien', translation: 'well / good' },
    { id: 'mal', lemma: 'mal', translation: 'bad / badly' },
    { id: 'muy', lemma: 'muy', translation: 'very' },
    { id: 'esto', lemma: 'esto', translation: 'this' },
    { id: 'yo', lemma: 'yo', translation: 'I' },
    { id: 'tu', lemma: 'tú', translation: 'you (informal)' },
    { id: 'usted', lemma: 'usted', translation: 'you (formal)' },
    { id: 'quien', lemma: 'quién', translation: 'who' },
    { id: 'que', lemma: 'qué', translation: 'what' },
    { id: 'es', lemma: 'es', translation: 'is' },
    { id: 'buenos-dias', lemma: 'buenos días', translation: 'good morning' },
    // Unit 2 — I want / I have
    { id: 'quiero', lemma: 'querer', translation: 'to want', forms: ['quiero', 'quieres'], hint: 'quiero (I want)' },
    { id: 'tengo', lemma: 'tener', translation: 'to have', forms: ['tengo', 'tienes'], hint: 'tengo (I have)' },
    { id: 'agua', lemma: 'agua', translation: 'water' },
    { id: 'te', lemma: 'té', translation: 'tea' },
    { id: 'cafe', lemma: 'café', translation: 'coffee' },
    { id: 'pan', lemma: 'pan', translation: 'bread' },
    { id: 'zumo', lemma: 'zumo', translation: 'juice' },
    { id: 'leche', lemma: 'leche', translation: 'milk' },
    { id: 'queso', lemma: 'queso', translation: 'cheese' },
    { id: 'manzana', lemma: 'manzana', translation: 'apple' },
    { id: 'sopa', lemma: 'sopa', translation: 'soup' },
    { id: 'casa', lemma: 'casa', translation: 'house / home' },
    { id: 'gato', lemma: 'gato', translation: 'cat' },
    { id: 'perro', lemma: 'perro', translation: 'dog' },
    { id: 'libro', lemma: 'libro', translation: 'book' },
    { id: 'telefono', lemma: 'teléfono', translation: 'phone' },
    { id: 'dinero', lemma: 'dinero', translation: 'money' },
    { id: 'un', lemma: 'un / una', translation: 'a / an' },
    // Unit 3 — people & verbs
    { id: 'el', lemma: 'él', translation: 'he' },
    { id: 'ella', lemma: 'ella', translation: 'she' },
    { id: 'nosotros', lemma: 'nosotros', translation: 'we' },
    { id: 'ellos', lemma: 'ellos', translation: 'they' },
    { id: 'madre', lemma: 'madre', translation: 'mother', forms: ['mamá'] },
    { id: 'padre', lemma: 'padre', translation: 'father', forms: ['papá'] },
    { id: 'hermano', lemma: 'hermano', translation: 'brother' },
    { id: 'hermana', lemma: 'hermana', translation: 'sister' },
    { id: 'amigo', lemma: 'amigo', translation: 'friend' },
    { id: 'persona', lemma: 'persona', translation: 'person' },
    { id: 'se', lemma: 'saber', translation: 'to know', forms: ['sé', 'sabes'], hint: 'sé (I know)' },
    { id: 'entiendo', lemma: 'entender', translation: 'to understand', forms: ['entiendo', 'entiendes'], hint: 'entiendo (I understand)' },
    { id: 'hablo', lemma: 'hablar', translation: 'to speak', forms: ['hablo', 'hablas', 'habla'], hint: 'hablo (I speak)' },
    { id: 'amo', lemma: 'amar', translation: 'to love', forms: ['amo', 'amas'], hint: 'amo (I love)' },
    { id: 'vivo', lemma: 'vivir', translation: 'to live', forms: ['vivo', 'vives', 'vive'], hint: 'vivo (I live)' },
    { id: 'trabajo-v', lemma: 'trabajar', translation: 'to work', forms: ['trabajo', 'trabaja'], hint: 'trabajo (I work)' },
    { id: 'espanol', lemma: 'español', translation: 'Spanish' },
    { id: 'ingles', lemma: 'inglés', translation: 'English' },
    // Unit 4 — places
    { id: 'donde', lemma: 'dónde', translation: 'where' },
    { id: 'aqui', lemma: 'aquí', translation: 'here' },
    { id: 'alli', lemma: 'allí', translation: 'there' },
    { id: 'esta', lemma: 'está', translation: 'is (location)' },
    { id: 'escuela', lemma: 'escuela', translation: 'school' },
    { id: 'trabajo-n', lemma: 'trabajo', translation: 'work / job' },
    { id: 'tienda', lemma: 'tienda', translation: 'shop / store' },
    { id: 'ciudad', lemma: 'ciudad', translation: 'city' },
    { id: 'calle', lemma: 'calle', translation: 'street' },
    { id: 'espana', lemma: 'España', translation: 'Spain' },
    { id: 'madrid', lemma: 'Madrid', translation: 'Madrid' },
    { id: 'metro-es', lemma: 'metro', translation: 'metro / subway' },
    { id: 'bano', lemma: 'baño', translation: 'bathroom' },
    { id: 'estacion', lemma: 'estación', translation: 'station' },
    { id: 'restaurante', lemma: 'restaurante', translation: 'restaurant' },
    // Unit 5 — numbers & time
    { id: 'uno', lemma: 'uno', translation: 'one' },
    { id: 'dos', lemma: 'dos', translation: 'two' },
    { id: 'tres', lemma: 'tres', translation: 'three' },
    { id: 'cuatro', lemma: 'cuatro', translation: 'four' },
    { id: 'cinco', lemma: 'cinco', translation: 'five' },
    { id: 'seis', lemma: 'seis', translation: 'six' },
    { id: 'siete', lemma: 'siete', translation: 'seven' },
    { id: 'ocho', lemma: 'ocho', translation: 'eight' },
    { id: 'nueve', lemma: 'nueve', translation: 'nine' },
    { id: 'diez', lemma: 'diez', translation: 'ten' },
    { id: 'hora', lemma: 'hora', translation: 'hour / time' },
    { id: 'dia', lemma: 'día', translation: 'day' },
    { id: 'noche', lemma: 'noche', translation: 'night' },
    { id: 'manana-time', lemma: 'mañana', translation: 'morning / tomorrow' },
    { id: 'tarde', lemma: 'tarde', translation: 'afternoon / evening' },
    { id: 'hoy', lemma: 'hoy', translation: 'today' },
    { id: 'ahora', lemma: 'ahora', translation: 'now' },
    { id: 'cuando', lemma: 'cuándo', translation: 'when' },
    { id: 'cuanto', lemma: 'cuánto', translation: 'how much' },
  ],
  patterns: [
    {
      id: 'que-es-esto',
      frame: '¿Qué es esto?',
      frameTranslation: 'What is this?',
      slots: [],
    },
    {
      id: 'esto-es-x',
      frame: 'Esto es ___',
      frameTranslation: 'This is ___',
      slots: [
        { vocabId: 'agua', form: 'agua', translation: 'water' },
        { vocabId: 'gato', form: 'un gato', translation: 'a cat' },
        { vocabId: 'casa', form: 'una casa', translation: 'a house' },
        { vocabId: 'libro', form: 'un libro', translation: 'a book' },
      ],
    },
    {
      id: 'quiero-x',
      frame: 'Quiero ___',
      frameTranslation: 'I want ___',
      slots: [
        { vocabId: 'te', form: 'té', translation: 'tea' },
        { vocabId: 'cafe', form: 'café', translation: 'coffee' },
        { vocabId: 'agua', form: 'agua', translation: 'water' },
        { vocabId: 'zumo', form: 'zumo', translation: 'juice' },
        { vocabId: 'pan', form: 'pan', translation: 'bread' },
        { vocabId: 'sopa', form: 'sopa', translation: 'soup' },
      ],
    },
    {
      id: 'tengo-x',
      frame: 'Tengo ___',
      frameTranslation: 'I have ___',
      slots: [
        { vocabId: 'gato', form: 'un gato', translation: 'a cat' },
        { vocabId: 'perro', form: 'un perro', translation: 'a dog' },
        { vocabId: 'libro', form: 'un libro', translation: 'a book' },
        { vocabId: 'telefono', form: 'un teléfono', translation: 'a phone' },
        { vocabId: 'dinero', form: 'dinero', translation: 'money' },
      ],
    },
    {
      id: 'amo-x',
      frame: 'Amo ___',
      frameTranslation: 'I love ___',
      slots: [
        { vocabId: 'madre', form: 'a mamá', translation: 'mom' },
        { vocabId: 'cafe', form: 'el café', translation: 'coffee' },
        { vocabId: 'espana', form: 'España', translation: 'Spain' },
      ],
    },
    {
      id: 'donde-esta-x',
      frame: '¿Dónde está ___?',
      frameTranslation: 'Where is ___?',
      slots: [
        { vocabId: 'bano', form: 'el baño', translation: 'the bathroom' },
        { vocabId: 'metro-es', form: 'el metro', translation: 'the metro' },
        { vocabId: 'estacion', form: 'la estación', translation: 'the station' },
        { vocabId: 'tienda', form: 'la tienda', translation: 'the shop' },
        { vocabId: 'restaurante', form: 'el restaurante', translation: 'the restaurant' },
      ],
    },
    {
      id: 'vivo-en-x',
      frame: 'Vivo en ___',
      frameTranslation: 'I live in ___',
      slots: [
        { vocabId: 'madrid', form: 'Madrid', translation: 'Madrid' },
        { vocabId: 'espana', form: 'España', translation: 'Spain' },
        { vocabId: 'ciudad', form: 'la ciudad', translation: 'the city' },
        { vocabId: 'casa', form: 'una casa', translation: 'a house' },
      ],
    },
  ],
  units: [
    {
      id: 'u1',
      title: 'Survival patterns',
      description: 'Greetings, yes/no, and your first sentences',
      skills: [
        {
          id: 'u1s1',
          title: 'Hello & thanks',
          icon: 'hand',
          lessons: [
            {
              id: 'u1s1l1',
              title: 'First words',
              vocabIds: ['hola', 'adios', 'si', 'no', 'gracias'],
              sentences: [
                { text: '¡Hola!', translation: 'Hello!', vocabIds: ['hola'] },
                { text: 'Sí, gracias.', translation: 'Yes, thank you.', vocabIds: ['si', 'gracias'] },
                { text: 'No, gracias.', translation: 'No, thank you.', vocabIds: ['no', 'gracias'] },
                { text: '¡Adiós!', translation: 'Goodbye!', vocabIds: ['adios'] },
              ],
            },
            {
              id: 'u1s1l2',
              title: 'Being polite',
              vocabIds: ['por-favor', 'perdon', 'buenos-dias'],
              sentences: [
                { text: '¡Buenos días!', translation: 'Good morning!', vocabIds: ['buenos-dias'] },
                { text: 'Perdón, por favor.', translation: 'Excuse me, please.', vocabIds: ['perdon', 'por-favor'] },
                { text: 'Gracias. — De nada.', translation: 'Thank you. — You are welcome.', vocabIds: ['gracias'] },
              ],
            },
          ],
        },
        {
          id: 'u1s2',
          title: 'This is…',
          icon: 'sparkles',
          lessons: [
            {
              id: 'u1s2l1',
              title: 'What is this?',
              vocabIds: ['esto', 'que', 'quien', 'yo', 'tu', 'es'],
              patternIds: ['que-es-esto', 'esto-es-x'],
              sentences: [
                { text: '¿Qué es esto?', translation: 'What is this?', vocabIds: ['que', 'es', 'esto'] },
                { text: 'Esto es una casa.', translation: 'This is a house.', vocabIds: ['esto', 'es', 'casa'] },
                { text: '¿Quién es?', translation: 'Who is it?', vocabIds: ['quien', 'es'] },
                { text: '¡Soy yo!', translation: 'It is me!', vocabIds: ['yo'] },
              ],
            },
            {
              id: 'u1s2l2',
              title: 'Good & bad',
              vocabIds: ['bien', 'mal', 'muy', 'usted'],
              sentences: [
                { text: '¡Muy bien!', translation: 'Very good!', vocabIds: ['muy', 'bien'] },
                { text: 'Esto está mal.', translation: 'This is bad.', vocabIds: ['esto', 'mal'] },
                { text: '¿Cómo está usted?', translation: 'How are you? (formal)', vocabIds: ['usted'] },
                { text: 'Bien, ¡gracias!', translation: 'Well, thanks!', vocabIds: ['bien', 'gracias'] },
              ],
            },
          ],
        },
      ],
    },
    {
      id: 'u2',
      title: 'I want / I have',
      description: 'Order food and talk about what you own',
      skills: [
        {
          id: 'u2s1',
          title: 'I want…',
          icon: 'coffee',
          lessons: [
            {
              id: 'u2s1l1',
              title: 'Drinks',
              vocabIds: ['quiero', 'agua', 'te', 'cafe', 'zumo'],
              patternIds: ['quiero-x'],
              sentences: [
                { text: 'Quiero té.', translation: 'I want tea.', vocabIds: ['quiero', 'te'] },
                { text: 'Quiero café.', translation: 'I want coffee.', vocabIds: ['quiero', 'cafe'] },
                { text: 'Quiero agua, por favor.', translation: 'I want water, please.', vocabIds: ['quiero', 'agua', 'por-favor'] },
              ],
            },
            {
              id: 'u2s1l2',
              title: 'Food',
              vocabIds: ['pan', 'leche', 'queso', 'manzana', 'sopa', 'un'],
              sentences: [
                { text: 'Quiero pan y queso.', translation: 'I want bread and cheese.', vocabIds: ['quiero', 'pan', 'queso'] },
                { text: 'Esto es leche.', translation: 'This is milk.', vocabIds: ['esto', 'es', 'leche'] },
                { text: 'Una manzana, por favor.', translation: 'An apple, please.', vocabIds: ['un', 'manzana', 'por-favor'] },
                { text: 'La sopa está muy bien.', translation: 'The soup is very good.', vocabIds: ['sopa', 'muy', 'bien'] },
              ],
            },
          ],
        },
        {
          id: 'u2s2',
          title: 'I have…',
          icon: 'package',
          lessons: [
            {
              id: 'u2s2l1',
              title: 'My things',
              vocabIds: ['tengo', 'casa', 'gato', 'perro', 'libro'],
              patternIds: ['tengo-x'],
              sentences: [
                { text: 'Tengo un gato.', translation: 'I have a cat.', vocabIds: ['tengo', 'gato'] },
                { text: 'Tengo una casa.', translation: 'I have a house.', vocabIds: ['tengo', 'casa'] },
                { text: 'Tengo un perro y un gato.', translation: 'I have a dog and a cat.', vocabIds: ['tengo', 'perro', 'gato'] },
              ],
            },
            {
              id: 'u2s2l2',
              title: 'Phone & money',
              vocabIds: ['telefono', 'dinero'],
              sentences: [
                { text: 'Tengo un teléfono.', translation: 'I have a phone.', vocabIds: ['tengo', 'telefono'] },
                { text: 'Tengo dinero.', translation: 'I have money.', vocabIds: ['tengo', 'dinero'] },
                { text: '¿Es un teléfono? ¡Sí!', translation: 'Is it a phone? Yes!', vocabIds: ['es', 'telefono', 'si'] },
              ],
            },
          ],
        },
      ],
    },
    {
      id: 'u3',
      title: 'People & verbs',
      description: 'Family, friends, and your first verbs',
      skills: [
        {
          id: 'u3s1',
          title: 'Family',
          icon: 'users',
          lessons: [
            {
              id: 'u3s1l1',
              title: 'Mom & dad',
              vocabIds: ['madre', 'padre', 'hermano', 'hermana', 'el', 'ella'],
              sentences: [
                { text: 'Esto es mamá y papá.', translation: 'This is mom and dad.', vocabIds: ['esto', 'madre', 'padre'] },
                { text: 'Él es hermano, ella es hermana.', translation: 'He is a brother, she is a sister.', vocabIds: ['el', 'hermano', 'ella', 'hermana'] },
                { text: 'Tengo un hermano.', translation: 'I have a brother.', vocabIds: ['tengo', 'hermano'] },
              ],
            },
            {
              id: 'u3s1l2',
              title: 'Friends & people',
              vocabIds: ['amigo', 'persona', 'nosotros', 'ellos', 'amo'],
              patternIds: ['amo-x'],
              sentences: [
                { text: 'Él es mi amigo.', translation: 'He is my friend.', vocabIds: ['el', 'amigo'] },
                { text: 'Amo a mamá.', translation: 'I love mom.', vocabIds: ['amo', 'madre'] },
                { text: 'Nosotros y ellos.', translation: 'We and they.', vocabIds: ['nosotros', 'ellos'] },
              ],
            },
          ],
        },
        {
          id: 'u3s2',
          title: 'First verbs',
          icon: 'message-circle',
          lessons: [
            {
              id: 'u3s2l1',
              title: 'Speak & understand',
              vocabIds: ['hablo', 'entiendo', 'se', 'espanol', 'ingles'],
              sentences: [
                { text: 'Hablo español.', translation: 'I speak Spanish.', vocabIds: ['hablo', 'espanol'] },
                { text: 'No entiendo.', translation: 'I do not understand.', vocabIds: ['entiendo'] },
                { text: '¿Hablas inglés?', translation: 'Do you speak English?', vocabIds: ['hablo', 'ingles'] },
                { text: 'Lo sé.', translation: 'I know.', vocabIds: ['se'] },
              ],
            },
            {
              id: 'u3s2l2',
              title: 'Live & work',
              vocabIds: ['vivo', 'trabajo-v'],
              sentences: [
                { text: 'Vivo aquí.', translation: 'I live here.', vocabIds: ['vivo', 'aqui'] },
                { text: 'Ella trabaja.', translation: 'She works.', vocabIds: ['ella', 'trabajo-v'] },
                { text: 'Trabajo en casa.', translation: 'I work at home.', vocabIds: ['trabajo-v', 'casa'] },
              ],
            },
          ],
        },
      ],
    },
    {
      id: 'u4',
      title: 'Places',
      description: 'Ask where things are and say where you live',
      skills: [
        {
          id: 'u4s1',
          title: 'Where is…?',
          icon: 'map-pin',
          lessons: [
            {
              id: 'u4s1l1',
              title: 'Here & there',
              vocabIds: ['donde', 'aqui', 'alli', 'esta', 'bano', 'metro-es'],
              patternIds: ['donde-esta-x'],
              sentences: [
                { text: '¿Dónde está el baño?', translation: 'Where is the bathroom?', vocabIds: ['donde', 'esta', 'bano'] },
                { text: 'El metro está allí.', translation: 'The metro is there.', vocabIds: ['metro-es', 'esta', 'alli'] },
                { text: '¡Estoy aquí!', translation: 'I am here!', vocabIds: ['aqui'] },
              ],
            },
            {
              id: 'u4s1l2',
              title: 'Around town',
              vocabIds: ['tienda', 'estacion', 'restaurante', 'calle'],
              sentences: [
                { text: '¿Dónde está la tienda?', translation: 'Where is the shop?', vocabIds: ['donde', 'esta', 'tienda'] },
                { text: 'La estación está aquí, el restaurante allí.', translation: 'The station is here, the restaurant there.', vocabIds: ['estacion', 'aqui', 'restaurante', 'alli'] },
                { text: 'Esto es una calle.', translation: 'This is a street.', vocabIds: ['esto', 'es', 'calle'] },
              ],
            },
          ],
        },
        {
          id: 'u4s2',
          title: 'I live in…',
          icon: 'home',
          lessons: [
            {
              id: 'u4s2l1',
              title: 'City life',
              vocabIds: ['ciudad', 'madrid', 'espana', 'escuela', 'trabajo-n'],
              patternIds: ['vivo-en-x'],
              sentences: [
                { text: 'Vivo en Madrid.', translation: 'I live in Madrid.', vocabIds: ['vivo', 'madrid'] },
                { text: 'Madrid es una ciudad en España.', translation: 'Madrid is a city in Spain.', vocabIds: ['madrid', 'es', 'ciudad', 'espana'] },
                { text: 'La escuela está allí.', translation: 'The school is there.', vocabIds: ['escuela', 'esta', 'alli'] },
              ],
            },
          ],
        },
      ],
    },
    {
      id: 'u5',
      title: 'Numbers & time',
      description: 'Count to ten and talk about your day',
      skills: [
        {
          id: 'u5s1',
          title: 'One to ten',
          icon: 'hash',
          lessons: [
            {
              id: 'u5s1l1',
              title: '1–5',
              vocabIds: ['uno', 'dos', 'tres', 'cuatro', 'cinco'],
              sentences: [
                { text: 'Uno, dos, tres.', translation: 'One, two, three.', vocabIds: ['uno', 'dos', 'tres'] },
                { text: 'Cuatro y cinco.', translation: 'Four and five.', vocabIds: ['cuatro', 'cinco'] },
                { text: 'Tengo dos gatos.', translation: 'I have two cats.', vocabIds: ['tengo', 'dos', 'gato'] },
              ],
            },
            {
              id: 'u5s1l2',
              title: '6–10',
              vocabIds: ['seis', 'siete', 'ocho', 'nueve', 'diez'],
              sentences: [
                { text: 'Seis, siete, ocho.', translation: 'Six, seven, eight.', vocabIds: ['seis', 'siete', 'ocho'] },
                { text: 'Nueve y diez.', translation: 'Nine and ten.', vocabIds: ['nueve', 'diez'] },
              ],
            },
          ],
        },
        {
          id: 'u5s2',
          title: 'My day',
          icon: 'clock',
          lessons: [
            {
              id: 'u5s2l1',
              title: 'Times of day',
              vocabIds: ['manana-time', 'dia', 'tarde', 'noche', 'hora'],
              sentences: [
                { text: 'Mañana, día, tarde, noche.', translation: 'Morning, day, afternoon, night.', vocabIds: ['manana-time', 'dia', 'tarde', 'noche'] },
                { text: '¿Qué hora es?', translation: 'What time is it?', vocabIds: ['que', 'hora', 'es'] },
              ],
            },
            {
              id: 'u5s2l2',
              title: 'Today & now',
              vocabIds: ['hoy', 'ahora', 'cuando', 'cuanto'],
              sentences: [
                { text: '¿Cuándo? ¿Hoy o mañana?', translation: 'When? Today or tomorrow?', vocabIds: ['cuando', 'hoy', 'manana-time'] },
                { text: '¡Ahora!', translation: 'Now!', vocabIds: ['ahora'] },
                { text: '¿Cuánto es esto?', translation: 'How much is this?', vocabIds: ['cuanto', 'es', 'esto'] },
              ],
            },
          ],
        },
      ],
    },
  ],
}
