import type { Course } from '../types'

export const ruCourse: Course = {
  id: 'ru',
  name: 'Russian',
  flag: '🇷🇺',
  ttsLang: 'ru-RU',
  vocab: [
    // Unit 1 — survival
    { id: 'privet', lemma: 'привет', translation: 'hi', hint: 'privyet' },
    { id: 'zdravstvuyte', lemma: 'здравствуйте', translation: 'hello (formal)', hint: 'zdrastvuytye' },
    { id: 'poka', lemma: 'пока', translation: 'bye', hint: 'paka' },
    { id: 'do-svidaniya', lemma: 'до свидания', translation: 'goodbye', hint: 'da svidaniya' },
    { id: 'da', lemma: 'да', translation: 'yes' },
    { id: 'net', lemma: 'нет', translation: 'no', hint: 'nyet' },
    { id: 'spasibo', lemma: 'спасибо', translation: 'thank you', hint: 'spasiba' },
    { id: 'pozhaluysta', lemma: 'пожалуйста', translation: 'please / you are welcome', hint: 'pazhalusta' },
    { id: 'izvinite', lemma: 'извините', translation: 'excuse me / sorry', hint: 'izvinitye' },
    { id: 'khorosho', lemma: 'хорошо', translation: 'good / okay', hint: 'kharasho' },
    { id: 'plokho', lemma: 'плохо', translation: 'bad', hint: 'plokha' },
    { id: 'ochen', lemma: 'очень', translation: 'very', hint: 'ochen' },
    { id: 'eto', lemma: 'это', translation: 'this / this is', hint: 'eta' },
    { id: 'ya', lemma: 'я', translation: 'I' },
    { id: 'ty', lemma: 'ты', translation: 'you (informal)' },
    { id: 'vy', lemma: 'вы', translation: 'you (formal/plural)' },
    { id: 'kto', lemma: 'кто', translation: 'who' },
    { id: 'chto', lemma: 'что', translation: 'what', hint: 'shto' },
    // Unit 2 — I want / I have
    { id: 'khochu', lemma: 'хотеть', translation: 'to want', forms: ['хочу', 'хочешь'], hint: 'khachu (I want)' },
    { id: 'u-menya-est', lemma: 'у меня есть', translation: 'I have', hint: 'u menya yest' },
    { id: 'mozhno', lemma: 'можно', translation: 'may I / is it possible', hint: 'mozhna' },
    { id: 'voda', lemma: 'вода', translation: 'water', forms: ['воду'], hint: 'vada' },
    { id: 'chay', lemma: 'чай', translation: 'tea' },
    { id: 'kofe', lemma: 'кофе', translation: 'coffee', hint: 'kofye' },
    { id: 'khleb', lemma: 'хлеб', translation: 'bread', hint: 'khlyep' },
    { id: 'sok', lemma: 'сок', translation: 'juice' },
    { id: 'moloko', lemma: 'молоко', translation: 'milk', hint: 'malako' },
    { id: 'syr', lemma: 'сыр', translation: 'cheese' },
    { id: 'yabloko', lemma: 'яблоко', translation: 'apple', hint: 'yablaka' },
    { id: 'sup', lemma: 'суп', translation: 'soup' },
    { id: 'dom', lemma: 'дом', translation: 'house / home' },
    { id: 'kot', lemma: 'кот', translation: 'cat' },
    { id: 'sobaka', lemma: 'собака', translation: 'dog', forms: ['собаку'], hint: 'sabaka' },
    { id: 'kniga', lemma: 'книга', translation: 'book', forms: ['книгу'], hint: 'kniga' },
    { id: 'telefon', lemma: 'телефон', translation: 'phone', hint: 'telefon' },
    { id: 'dengi', lemma: 'деньги', translation: 'money', hint: 'dyengi' },
    // Unit 3 — people & verbs
    { id: 'on', lemma: 'он', translation: 'he' },
    { id: 'ona', lemma: 'она', translation: 'she', hint: 'ana' },
    { id: 'my', lemma: 'мы', translation: 'we' },
    { id: 'oni', lemma: 'они', translation: 'they', hint: 'ani' },
    { id: 'mama', lemma: 'мама', translation: 'mom' },
    { id: 'papa', lemma: 'папа', translation: 'dad' },
    { id: 'brat', lemma: 'брат', translation: 'brother' },
    { id: 'sestra', lemma: 'сестра', translation: 'sister', hint: 'sestra' },
    { id: 'drug', lemma: 'друг', translation: 'friend', hint: 'druk' },
    { id: 'chelovek', lemma: 'человек', translation: 'person', hint: 'chelavyek' },
    { id: 'znayu', lemma: 'знать', translation: 'to know', forms: ['знаю', 'знаешь'], hint: 'znayu (I know)' },
    { id: 'ponimayu', lemma: 'понимать', translation: 'to understand', forms: ['понимаю', 'понимаешь'], hint: 'panimayu (I understand)' },
    { id: 'govoryu', lemma: 'говорить', translation: 'to speak', forms: ['говорю', 'говоришь', 'говорит'], hint: 'gavaryu (I speak)' },
    { id: 'lyublyu', lemma: 'любить', translation: 'to love', forms: ['люблю', 'любишь', 'любит'], hint: 'lyublyu (I love)' },
    { id: 'zhivu', lemma: 'жить', translation: 'to live', forms: ['живу', 'живёшь', 'живёт'], hint: 'zhivu (I live)' },
    { id: 'rabotayu', lemma: 'работать', translation: 'to work', forms: ['работаю', 'работает'], hint: 'rabotayu (I work)' },
    { id: 'po-russki', lemma: 'по-русски', translation: 'in Russian', hint: 'pa-russki' },
    { id: 'po-angliyski', lemma: 'по-английски', translation: 'in English', hint: 'pa-angliyski' },
    // Unit 4 — places
    { id: 'gde', lemma: 'где', translation: 'where', hint: 'gdye' },
    { id: 'zdes', lemma: 'здесь', translation: 'here', hint: 'zdyes' },
    { id: 'tam', lemma: 'там', translation: 'there' },
    { id: 'shkola', lemma: 'школа', translation: 'school', forms: ['школе'] },
    { id: 'rabota', lemma: 'работа', translation: 'work / job', forms: ['работе'], hint: 'rabota' },
    { id: 'magazin', lemma: 'магазин', translation: 'shop / store', forms: ['магазине'], hint: 'magazin' },
    { id: 'gorod', lemma: 'город', translation: 'city', forms: ['городе'], hint: 'gorat' },
    { id: 'ulitsa', lemma: 'улица', translation: 'street', forms: ['улице'], hint: 'ulitsa' },
    { id: 'rossiya', lemma: 'Россия', translation: 'Russia', forms: ['России'], hint: 'Rassiya' },
    { id: 'moskva', lemma: 'Москва', translation: 'Moscow', forms: ['Москве'], hint: 'Maskva' },
    { id: 'metro', lemma: 'метро', translation: 'metro / subway' },
    { id: 'tualet', lemma: 'туалет', translation: 'toilet / restroom', hint: 'tualyet' },
    { id: 'vokzal', lemma: 'вокзал', translation: 'train station', hint: 'vakzal' },
    { id: 'restoran', lemma: 'ресторан', translation: 'restaurant', forms: ['ресторане'], hint: 'restaran' },
    // Unit 5 — numbers & time
    { id: 'odin', lemma: 'один', translation: 'one', hint: 'adin' },
    { id: 'dva', lemma: 'два', translation: 'two' },
    { id: 'tri', lemma: 'три', translation: 'three' },
    { id: 'chetyre', lemma: 'четыре', translation: 'four', hint: 'chetyrye' },
    { id: 'pyat', lemma: 'пять', translation: 'five', hint: 'pyat' },
    { id: 'shest', lemma: 'шесть', translation: 'six', hint: 'shest' },
    { id: 'sem', lemma: 'семь', translation: 'seven', hint: 'syem' },
    { id: 'vosem', lemma: 'восемь', translation: 'eight', hint: 'vosem' },
    { id: 'devyat', lemma: 'девять', translation: 'nine', hint: 'dyevyat' },
    { id: 'desyat', lemma: 'десять', translation: 'ten', hint: 'dyesyat' },
    { id: 'chas', lemma: 'час', translation: 'hour / one o’clock', forms: ['часа', 'часов'] },
    { id: 'den', lemma: 'день', translation: 'day', hint: 'dyen' },
    { id: 'noch', lemma: 'ночь', translation: 'night', hint: 'noch' },
    { id: 'utro', lemma: 'утро', translation: 'morning', hint: 'utra' },
    { id: 'vecher', lemma: 'вечер', translation: 'evening', hint: 'vyecher' },
    { id: 'segodnya', lemma: 'сегодня', translation: 'today', hint: 'sevodnya' },
    { id: 'zavtra', lemma: 'завтра', translation: 'tomorrow', hint: 'zaftra' },
    { id: 'seychas', lemma: 'сейчас', translation: 'now', hint: 'seychas' },
    { id: 'kogda', lemma: 'когда', translation: 'when', hint: 'kagda' },
    { id: 'skolko', lemma: 'сколько', translation: 'how much / how many', hint: 'skolka' },
  ],
  patterns: [
    {
      id: 'chto-eto',
      frame: 'Что это?',
      frameTranslation: 'What is this?',
      slots: [],
    },
    {
      id: 'eto-x',
      frame: 'Это ___',
      frameTranslation: 'This is ___',
      slots: [
        { vocabId: 'voda', form: 'вода', translation: 'water' },
        { vocabId: 'kot', form: 'кот', translation: 'a cat' },
        { vocabId: 'dom', form: 'дом', translation: 'a house' },
        { vocabId: 'kniga', form: 'книга', translation: 'a book' },
        { vocabId: 'mama', form: 'мама', translation: 'mom' },
      ],
    },
    {
      id: 'ya-khochu-x',
      frame: 'Я хочу ___',
      frameTranslation: 'I want ___',
      slots: [
        { vocabId: 'chay', form: 'чай', translation: 'tea' },
        { vocabId: 'kofe', form: 'кофе', translation: 'coffee' },
        { vocabId: 'voda', form: 'воду', translation: 'water' },
        { vocabId: 'sok', form: 'сок', translation: 'juice' },
        { vocabId: 'khleb', form: 'хлеб', translation: 'bread' },
        { vocabId: 'sup', form: 'суп', translation: 'soup' },
      ],
    },
    {
      id: 'u-menya-est-x',
      frame: 'У меня есть ___',
      frameTranslation: 'I have ___',
      slots: [
        { vocabId: 'kot', form: 'кот', translation: 'a cat' },
        { vocabId: 'sobaka', form: 'собака', translation: 'a dog' },
        { vocabId: 'kniga', form: 'книга', translation: 'a book' },
        { vocabId: 'telefon', form: 'телефон', translation: 'a phone' },
        { vocabId: 'dengi', form: 'деньги', translation: 'money' },
      ],
    },
    {
      id: 'mozhno-x',
      frame: 'Можно ___?',
      frameTranslation: 'May I have ___?',
      slots: [
        { vocabId: 'chay', form: 'чай', translation: 'tea' },
        { vocabId: 'kofe', form: 'кофе', translation: 'coffee' },
        { vocabId: 'moloko', form: 'молоко', translation: 'milk' },
        { vocabId: 'syr', form: 'сыр', translation: 'cheese' },
      ],
    },
    {
      id: 'ya-lyublyu-x',
      frame: 'Я люблю ___',
      frameTranslation: 'I love ___',
      slots: [
        { vocabId: 'mama', form: 'маму', translation: 'mom' },
        { vocabId: 'chay', form: 'чай', translation: 'tea' },
        { vocabId: 'sobaka', form: 'собаку', translation: 'the dog' },
        { vocabId: 'rossiya', form: 'Россию', translation: 'Russia' },
      ],
    },
    {
      id: 'gde-x',
      frame: 'Где ___?',
      frameTranslation: 'Where is ___?',
      slots: [
        { vocabId: 'tualet', form: 'туалет', translation: 'the toilet' },
        { vocabId: 'metro', form: 'метро', translation: 'the metro' },
        { vocabId: 'vokzal', form: 'вокзал', translation: 'the train station' },
        { vocabId: 'magazin', form: 'магазин', translation: 'the shop' },
        { vocabId: 'restoran', form: 'ресторан', translation: 'the restaurant' },
      ],
    },
    {
      id: 'ya-zhivu-v-x',
      frame: 'Я живу в ___',
      frameTranslation: 'I live in ___',
      slots: [
        { vocabId: 'moskva', form: 'Москве', translation: 'Moscow' },
        { vocabId: 'rossiya', form: 'России', translation: 'Russia' },
        { vocabId: 'gorod', form: 'городе', translation: 'the city' },
        { vocabId: 'dom', form: 'доме', translation: 'the house' },
      ],
    },
  ],
  units: [
    {
      id: 'u1',
      title: 'Survival patterns',
      description: 'Greetings, yes/no, and your first sentences',
      skills: [
        {
          id: 'u1s1',
          title: 'Hello & thanks',
          icon: 'hand',
          lessons: [
            {
              id: 'u1s1l1',
              title: 'First words',
              vocabIds: ['privet', 'poka', 'da', 'net', 'spasibo'],
              sentences: [
                { text: 'Привет!', translation: 'Hi!', vocabIds: ['privet'] },
                { text: 'Да, спасибо.', translation: 'Yes, thank you.', vocabIds: ['da', 'spasibo'] },
                { text: 'Нет, спасибо.', translation: 'No, thank you.', vocabIds: ['net', 'spasibo'] },
                { text: 'Пока!', translation: 'Bye!', vocabIds: ['poka'] },
              ],
            },
            {
              id: 'u1s1l2',
              title: 'Being polite',
              vocabIds: ['zdravstvuyte', 'do-svidaniya', 'pozhaluysta', 'izvinite'],
              sentences: [
                { text: 'Здравствуйте!', translation: 'Hello!', vocabIds: ['zdravstvuyte'] },
                { text: 'Извините, пожалуйста.', translation: 'Excuse me, please.', vocabIds: ['izvinite', 'pozhaluysta'] },
                { text: 'Спасибо! — Пожалуйста.', translation: 'Thank you! — You are welcome.', vocabIds: ['spasibo', 'pozhaluysta'] },
                { text: 'До свидания!', translation: 'Goodbye!', vocabIds: ['do-svidaniya'] },
              ],
            },
          ],
        },
        {
          id: 'u1s2',
          title: 'This is…',
          icon: 'sparkles',
          lessons: [
            {
              id: 'u1s2l1',
              title: 'What is this?',
              vocabIds: ['eto', 'chto', 'kto', 'ya', 'ty'],
              patternIds: ['chto-eto', 'eto-x'],
              sentences: [
                { text: 'Что это?', translation: 'What is this?', vocabIds: ['chto', 'eto'] },
                { text: 'Это дом.', translation: 'This is a house.', vocabIds: ['eto', 'dom'] },
                { text: 'Кто это?', translation: 'Who is this?', vocabIds: ['kto', 'eto'] },
                { text: 'Это я!', translation: 'It is me!', vocabIds: ['eto', 'ya'] },
              ],
            },
            {
              id: 'u1s2l2',
              title: 'Good & bad',
              vocabIds: ['khorosho', 'plokho', 'ochen', 'vy'],
              sentences: [
                { text: 'Очень хорошо!', translation: 'Very good!', vocabIds: ['ochen', 'khorosho'] },
                { text: 'Это плохо.', translation: 'This is bad.', vocabIds: ['eto', 'plokho'] },
                { text: 'Как вы?', translation: 'How are you?', vocabIds: ['vy'] },
                { text: 'Хорошо, спасибо!', translation: 'Good, thanks!', vocabIds: ['khorosho', 'spasibo'] },
              ],
            },
          ],
        },
      ],
    },
    {
      id: 'u2',
      title: 'I want / I have',
      description: 'Order food and talk about what you own',
      skills: [
        {
          id: 'u2s1',
          title: 'I want…',
          icon: 'coffee',
          lessons: [
            {
              id: 'u2s1l1',
              title: 'Drinks',
              vocabIds: ['khochu', 'voda', 'chay', 'kofe', 'sok'],
              patternIds: ['ya-khochu-x'],
              sentences: [
                { text: 'Я хочу чай.', translation: 'I want tea.', vocabIds: ['khochu', 'chay'] },
                { text: 'Я хочу кофе.', translation: 'I want coffee.', vocabIds: ['khochu', 'kofe'] },
                { text: 'Я хочу воду, пожалуйста.', translation: 'I want water, please.', vocabIds: ['khochu', 'voda', 'pozhaluysta'] },
              ],
            },
            {
              id: 'u2s1l2',
              title: 'Food',
              vocabIds: ['khleb', 'moloko', 'syr', 'yabloko', 'sup', 'mozhno'],
              patternIds: ['mozhno-x'],
              sentences: [
                { text: 'Можно хлеб?', translation: 'May I have bread?', vocabIds: ['mozhno', 'khleb'] },
                { text: 'Я хочу суп и сыр.', translation: 'I want soup and cheese.', vocabIds: ['khochu', 'sup', 'syr'] },
                { text: 'Это молоко.', translation: 'This is milk.', vocabIds: ['eto', 'moloko'] },
                { text: 'Можно яблоко, пожалуйста?', translation: 'May I have an apple, please?', vocabIds: ['mozhno', 'yabloko', 'pozhaluysta'] },
              ],
            },
          ],
        },
        {
          id: 'u2s2',
          title: 'I have…',
          icon: 'package',
          lessons: [
            {
              id: 'u2s2l1',
              title: 'My things',
              vocabIds: ['u-menya-est', 'dom', 'kot', 'sobaka', 'kniga'],
              patternIds: ['u-menya-est-x'],
              sentences: [
                { text: 'У меня есть кот.', translation: 'I have a cat.', vocabIds: ['u-menya-est', 'kot'] },
                { text: 'У меня есть дом.', translation: 'I have a house.', vocabIds: ['u-menya-est', 'dom'] },
                { text: 'У меня есть собака и кот.', translation: 'I have a dog and a cat.', vocabIds: ['u-menya-est', 'sobaka', 'kot'] },
              ],
            },
            {
              id: 'u2s2l2',
              title: 'Phone & money',
              vocabIds: ['telefon', 'dengi'],
              sentences: [
                { text: 'У меня есть телефон.', translation: 'I have a phone.', vocabIds: ['u-menya-est', 'telefon'] },
                { text: 'У меня есть деньги.', translation: 'I have money.', vocabIds: ['u-menya-est', 'dengi'] },
                { text: 'Это телефон? Да!', translation: 'Is this a phone? Yes!', vocabIds: ['eto', 'telefon', 'da'] },
              ],
            },
          ],
        },
      ],
    },
    {
      id: 'u3',
      title: 'People & verbs',
      description: 'Family, friends, and your first verbs',
      skills: [
        {
          id: 'u3s1',
          title: 'Family',
          icon: 'users',
          lessons: [
            {
              id: 'u3s1l1',
              title: 'Mom & dad',
              vocabIds: ['mama', 'papa', 'brat', 'sestra', 'on', 'ona'],
              sentences: [
                { text: 'Это мама и папа.', translation: 'This is mom and dad.', vocabIds: ['eto', 'mama', 'papa'] },
                { text: 'Он брат, она сестра.', translation: 'He is a brother, she is a sister.', vocabIds: ['on', 'brat', 'ona', 'sestra'] },
                { text: 'У меня есть брат.', translation: 'I have a brother.', vocabIds: ['u-menya-est', 'brat'] },
              ],
            },
            {
              id: 'u3s1l2',
              title: 'Friends & people',
              vocabIds: ['drug', 'chelovek', 'my', 'oni', 'lyublyu'],
              patternIds: ['ya-lyublyu-x'],
              sentences: [
                { text: 'Он мой друг.', translation: 'He is my friend.', vocabIds: ['on', 'drug'] },
                { text: 'Я люблю маму.', translation: 'I love mom.', vocabIds: ['lyublyu', 'mama'] },
                { text: 'Мы и они.', translation: 'We and they.', vocabIds: ['my', 'oni'] },
              ],
            },
          ],
        },
        {
          id: 'u3s2',
          title: 'First verbs',
          icon: 'message-circle',
          lessons: [
            {
              id: 'u3s2l1',
              title: 'Speak & understand',
              vocabIds: ['govoryu', 'ponimayu', 'znayu', 'po-russki', 'po-angliyski'],
              sentences: [
                { text: 'Я говорю по-русски.', translation: 'I speak Russian.', vocabIds: ['govoryu', 'po-russki'] },
                { text: 'Я не понимаю.', translation: 'I do not understand.', vocabIds: ['ponimayu'] },
                { text: 'Вы говорите по-английски?', translation: 'Do you speak English?', vocabIds: ['vy', 'govoryu', 'po-angliyski'] },
                { text: 'Я знаю.', translation: 'I know.', vocabIds: ['znayu'] },
              ],
            },
            {
              id: 'u3s2l2',
              title: 'Live & work',
              vocabIds: ['zhivu', 'rabotayu'],
              sentences: [
                { text: 'Я живу здесь.', translation: 'I live here.', vocabIds: ['zhivu', 'zdes'] },
                { text: 'Она работает.', translation: 'She works.', vocabIds: ['ona', 'rabotayu'] },
                { text: 'Я работаю дома.', translation: 'I work at home.', vocabIds: ['rabotayu', 'dom'] },
              ],
            },
          ],
        },
      ],
    },
    {
      id: 'u4',
      title: 'Places',
      description: 'Ask where things are and say where you live',
      skills: [
        {
          id: 'u4s1',
          title: 'Where is…?',
          icon: 'map-pin',
          lessons: [
            {
              id: 'u4s1l1',
              title: 'Here & there',
              vocabIds: ['gde', 'zdes', 'tam', 'tualet', 'metro'],
              patternIds: ['gde-x'],
              sentences: [
                { text: 'Где туалет?', translation: 'Where is the toilet?', vocabIds: ['gde', 'tualet'] },
                { text: 'Метро там.', translation: 'The metro is there.', vocabIds: ['metro', 'tam'] },
                { text: 'Я здесь!', translation: 'I am here!', vocabIds: ['ya', 'zdes'] },
              ],
            },
            {
              id: 'u4s1l2',
              title: 'Around town',
              vocabIds: ['magazin', 'vokzal', 'restoran', 'ulitsa'],
              sentences: [
                { text: 'Где магазин?', translation: 'Where is the shop?', vocabIds: ['gde', 'magazin'] },
                { text: 'Вокзал здесь, ресторан там.', translation: 'The station is here, the restaurant is there.', vocabIds: ['vokzal', 'zdes', 'restoran', 'tam'] },
                { text: 'Это улица.', translation: 'This is a street.', vocabIds: ['eto', 'ulitsa'] },
              ],
            },
          ],
        },
        {
          id: 'u4s2',
          title: 'I live in…',
          icon: 'home',
          lessons: [
            {
              id: 'u4s2l1',
              title: 'City life',
              vocabIds: ['gorod', 'moskva', 'rossiya', 'shkola', 'rabota'],
              patternIds: ['ya-zhivu-v-x'],
              sentences: [
                { text: 'Я живу в Москве.', translation: 'I live in Moscow.', vocabIds: ['zhivu', 'moskva'] },
                { text: 'Москва — это город в России.', translation: 'Moscow is a city in Russia.', vocabIds: ['moskva', 'eto', 'gorod', 'rossiya'] },
                { text: 'Школа там.', translation: 'The school is there.', vocabIds: ['shkola', 'tam'] },
              ],
            },
          ],
        },
      ],
    },
    {
      id: 'u5',
      title: 'Numbers & time',
      description: 'Count to ten and talk about your day',
      skills: [
        {
          id: 'u5s1',
          title: 'One to ten',
          icon: 'hash',
          lessons: [
            {
              id: 'u5s1l1',
              title: '1–5',
              vocabIds: ['odin', 'dva', 'tri', 'chetyre', 'pyat'],
              sentences: [
                { text: 'Один, два, три.', translation: 'One, two, three.', vocabIds: ['odin', 'dva', 'tri'] },
                { text: 'Четыре и пять.', translation: 'Four and five.', vocabIds: ['chetyre', 'pyat'] },
                { text: 'У меня есть два кота.', translation: 'I have two cats.', vocabIds: ['u-menya-est', 'dva', 'kot'] },
              ],
            },
            {
              id: 'u5s1l2',
              title: '6–10',
              vocabIds: ['shest', 'sem', 'vosem', 'devyat', 'desyat'],
              sentences: [
                { text: 'Шесть, семь, восемь.', translation: 'Six, seven, eight.', vocabIds: ['shest', 'sem', 'vosem'] },
                { text: 'Девять и десять.', translation: 'Nine and ten.', vocabIds: ['devyat', 'desyat'] },
              ],
            },
          ],
        },
        {
          id: 'u5s2',
          title: 'My day',
          icon: 'clock',
          lessons: [
            {
              id: 'u5s2l1',
              title: 'Times of day',
              vocabIds: ['utro', 'den', 'vecher', 'noch', 'chas'],
              sentences: [
                { text: 'Утро, день, вечер, ночь.', translation: 'Morning, day, evening, night.', vocabIds: ['utro', 'den', 'vecher', 'noch'] },
                { text: 'Сейчас час.', translation: 'It is one o’clock now.', vocabIds: ['seychas', 'chas'] },
              ],
            },
            {
              id: 'u5s2l2',
              title: 'Today & tomorrow',
              vocabIds: ['segodnya', 'zavtra', 'seychas', 'kogda', 'skolko'],
              sentences: [
                { text: 'Когда? Сегодня или завтра?', translation: 'When? Today or tomorrow?', vocabIds: ['kogda', 'segodnya', 'zavtra'] },
                { text: 'Сейчас!', translation: 'Now!', vocabIds: ['seychas'] },
                { text: 'Сколько это?', translation: 'How much is this?', vocabIds: ['skolko', 'eto'] },
              ],
            },
          ],
        },
      ],
    },
  ],
}
