import type { Course } from '../types'

export const ruCourse: Course = {
  id: 'ru',
  name: 'Russian',
  flag: '🇷🇺',
  ttsLang: 'ru-RU',
  vocab: [
    // Unit 1 — survival
    { id: 'privet', lemma: 'привет', translation: 'hi', hint: 'privyet' },
    { id: 'zdravstvuyte', lemma: 'здравствуйте', translation: 'hello (formal)', hint: 'zdrastvuytye' },
    { id: 'poka', lemma: 'пока', translation: 'bye', hint: 'paka' },
    { id: 'do-svidaniya', lemma: 'до свидания', translation: 'goodbye', hint: 'da svidaniya' },
    { id: 'da', lemma: 'да', translation: 'yes' },
    { id: 'net', lemma: 'нет', translation: 'no', hint: 'nyet' },
    { id: 'spasibo', lemma: 'спасибо', translation: 'thank you', hint: 'spasiba' },
    { id: 'pozhaluysta', lemma: 'пожалуйста', translation: 'please / you are welcome', hint: 'pazhalusta' },
    { id: 'izvinite', lemma: 'извините', translation: 'excuse me / sorry', hint: 'izvinitye' },
    { id: 'khorosho', lemma: 'хорошо', translation: 'good / okay', hint: 'kharasho' },
    { id: 'plokho', lemma: 'плохо', translation: 'bad', hint: 'plokha' },
    { id: 'ochen', lemma: 'очень', translation: 'very', hint: 'ochen' },
    { id: 'eto', lemma: 'это', translation: 'this / this is', hint: 'eta' },
    { id: 'ya', lemma: 'я', translation: 'I' },
    { id: 'ty', lemma: 'ты', translation: 'you (informal)' },
    { id: 'vy', lemma: 'вы', translation: 'you (formal/plural)' },
    { id: 'kto', lemma: 'кто', translation: 'who' },
    { id: 'chto', lemma: 'что', translation: 'what', hint: 'shto' },
    // Unit 2 — I want / I have
    { id: 'khochu', lemma: 'хотеть', translation: 'to want', forms: ['хочу', 'хочешь'], hint: 'khachu (I want)' },
    { id: 'u-menya-est', lemma: 'у меня есть', translation: 'I have', hint: 'u menya yest' },
    { id: 'mozhno', lemma: 'можно', translation: 'may I / is it possible', hint: 'mozhna' },
    { id: 'voda', lemma: 'вода', translation: 'water', forms: ['воду'], hint: 'vada' },
    { id: 'chay', lemma: 'чай', translation: 'tea' },
    { id: 'kofe', lemma: 'кофе', translation: 'coffee', hint: 'kofye' },
    { id: 'khleb', lemma: 'хлеб', translation: 'bread', hint: 'khlyep' },
    { id: 'sok', lemma: 'сок', translation: 'juice' },
    { id: 'moloko', lemma: 'молоко', translation: 'milk', hint: 'malako' },
    { id: 'syr', lemma: 'сыр', translation: 'cheese' },
    { id: 'yabloko', lemma: 'яблоко', translation: 'apple', hint: 'yablaka' },
    { id: 'sup', lemma: 'суп', translation: 'soup' },
    { id: 'dom', lemma: 'дом', translation: 'house / home' },
    { id: 'kot', lemma: 'кот', translation: 'cat' },
    { id: 'sobaka', lemma: 'собака', translation: 'dog', forms: ['собаку'], hint: 'sabaka' },
    { id: 'kniga', lemma: 'книга', translation: 'book', forms: ['книгу'], hint: 'kniga' },
    { id: 'telefon', lemma: 'телефон', translation: 'phone', hint: 'telefon' },
    { id: 'dengi', lemma: 'деньги', translation: 'money', hint: 'dyengi' },
    // Unit 3 — people & verbs
    { id: 'on', lemma: 'он', translation: 'he' },
    { id: 'ona', lemma: 'она', translation: 'she', hint: 'ana' },
    { id: 'my', lemma: 'мы', translation: 'we' },
    { id: 'oni', lemma: 'они', translation: 'they', hint: 'ani' },
    { id: 'mama', lemma: 'мама', translation: 'mom' },
    { id: 'papa', lemma: 'папа', translation: 'dad' },
    { id: 'brat', lemma: 'брат', translation: 'brother' },
    { id: 'sestra', lemma: 'сестра', translation: 'sister', hint: 'sestra' },
    { id: 'drug', lemma: 'друг', translation: 'friend', hint: 'druk' },
    { id: 'chelovek', lemma: 'человек', translation: 'person', hint: 'chelavyek' },
    { id: 'znayu', lemma: 'знать', translation: 'to know', forms: ['знаю', 'знаешь'], hint: 'znayu (I know)' },
    { id: 'ponimayu', lemma: 'понимать', translation: 'to understand', forms: ['понимаю', 'понимаешь'], hint: 'panimayu (I understand)' },
    { id: 'govoryu', lemma: 'говорить', translation: 'to speak', forms: ['говорю', 'говоришь', 'говорит'], hint: 'gavaryu (I speak)' },
    { id: 'lyublyu', lemma: 'любить', translation: 'to love', forms: ['люблю', 'любишь', 'любит'], hint: 'lyublyu (I love)' },
    { id: 'zhivu', lemma: 'жить', translation: 'to live', forms: ['живу', 'живёшь', 'живёт'], hint: 'zhivu (I live)' },
    { id: 'rabotayu', lemma: 'работать', translation: 'to work', forms: ['работаю', 'работает'], hint: 'rabotayu (I work)' },
    { id: 'po-russki', lemma: 'по-русски', translation: 'in Russian', hint: 'pa-russki' },
    { id: 'po-angliyski', lemma: 'по-английски', translation: 'in English', hint: 'pa-angliyski' },
    // Unit 4 — places
    { id: 'gde', lemma: 'где', translation: 'where', hint: 'gdye' },
    { id: 'zdes', lemma: 'здесь', translation: 'here', hint: 'zdyes' },
    { id: 'tam', lemma: 'там', translation: 'there' },
    { id: 'shkola', lemma: 'школа', translation: 'school', forms: ['школе'] },
    { id: 'rabota', lemma: 'работа', translation: 'work / job', forms: ['работе'], hint: 'rabota' },
    { id: 'magazin', lemma: 'магазин', translation: 'shop / store', forms: ['магазине'], hint: 'magazin' },
    { id: 'gorod', lemma: 'город', translation: 'city', forms: ['городе'], hint: 'gorat' },
    { id: 'ulitsa', lemma: 'улица', translation: 'street', forms: ['улице'], hint: 'ulitsa' },
    { id: 'rossiya', lemma: 'Россия', translation: 'Russia', forms: ['России'], hint: 'Rassiya' },
    { id: 'moskva', lemma: 'Москва', translation: 'Moscow', forms: ['Москве'], hint: 'Maskva' },
    { id: 'metro', lemma: 'метро', translation: 'metro / subway' },
    { id: 'tualet', lemma: 'туалет', translation: 'toilet / restroom', hint: 'tualyet' },
    { id: 'vokzal', lemma: 'вокзал', translation: 'train station', hint: 'vakzal' },
    { id: 'restoran', lemma: 'ресторан', translation: 'restaurant', forms: ['ресторане'], hint: 'restaran' },
    // Unit 5 — numbers & time
    { id: 'odin', lemma: 'один', translation: 'one', hint: 'adin' },
    { id: 'dva', lemma: 'два', translation: 'two' },
    { id: 'tri', lemma: 'три', translation: 'three' },
    { id: 'chetyre', lemma: 'четыре', translation: 'four', hint: 'chetyrye' },
    { id: 'pyat', lemma: 'пять', translation: 'five', hint: 'pyat' },
    { id: 'shest', lemma: 'шесть', translation: 'six', hint: 'shest' },
    { id: 'sem', lemma: 'семь', translation: 'seven', hint: 'syem' },
    { id: 'vosem', lemma: 'восемь', translation: 'eight', hint: 'vosem' },
    { id: 'devyat', lemma: 'девять', translation: 'nine', hint: 'dyevyat' },
    { id: 'desyat', lemma: 'десять', translation: 'ten', hint: 'dyesyat' },
    { id: 'chas', lemma: 'час', translation: 'hour / one o’clock', forms: ['часа', 'часов'] },
    { id: 'den', lemma: 'день', translation: 'day', hint: 'dyen' },
    { id: 'noch', lemma: 'ночь', translation: 'night', hint: 'noch' },
    { id: 'utro', lemma: 'утро', translation: 'morning', hint: 'utra' },
    { id: 'vecher', lemma: 'вечер', translation: 'evening', hint: 'vyecher' },
    { id: 'segodnya', lemma: 'сегодня', translation: 'today', hint: 'sevodnya' },
    { id: 'zavtra', lemma: 'завтра', translation: 'tomorrow', hint: 'zaftra' },
    { id: 'seychas', lemma: 'сейчас', translation: 'now', hint: 'seychas' },
    { id: 'kogda', lemma: 'когда', translation: 'when', hint: 'kagda' },
    { id: 'skolko', lemma: 'сколько', translation: 'how much / how many', hint: 'skolka' },
    // Unit 6 — describing things
    { id: 'krasny', lemma: 'красный', translation: 'red', hint: 'krasny' },
    { id: 'siniy', lemma: 'синий', translation: 'blue', hint: 'siniy' },
    { id: 'zelyony', lemma: 'зелёный', translation: 'green', hint: 'zelyony' },
    { id: 'zholty', lemma: 'жёлтый', translation: 'yellow', hint: 'zholty' },
    { id: 'cherny', lemma: 'чёрный', translation: 'black', hint: 'chorny' },
    { id: 'bely', lemma: 'белый', translation: 'white', hint: 'byely' },
    { id: 'bolshoy', lemma: 'большой', translation: 'big', hint: 'balshoy' },
    { id: 'malenkiy', lemma: 'маленький', translation: 'small', hint: 'malenkiy' },
    { id: 'novy', lemma: 'новый', translation: 'new', hint: 'novy' },
    { id: 'stary', lemma: 'старый', translation: 'old', hint: 'stary' },
    { id: 'krasivy', lemma: 'красивый', translation: 'beautiful', forms: ['красиво'], hint: 'krasivy' },
    { id: 'vkusny', lemma: 'вкусный', translation: 'tasty / delicious', forms: ['вкусно'], hint: 'fkusny' },
    // Unit 7 — days & questions
    { id: 'ponedelnik', lemma: 'понедельник', translation: 'Monday', hint: 'panedelnik' },
    { id: 'vtornik', lemma: 'вторник', translation: 'Tuesday', hint: 'ftornik' },
    { id: 'sreda', lemma: 'среда', translation: 'Wednesday', hint: 'sreda' },
    { id: 'chetverg', lemma: 'четверг', translation: 'Thursday', hint: 'chetverk' },
    { id: 'pyatnitsa', lemma: 'пятница', translation: 'Friday', hint: 'pyatnitsa' },
    { id: 'subbota', lemma: 'суббота', translation: 'Saturday', hint: 'subbota' },
    { id: 'voskresene', lemma: 'воскресенье', translation: 'Sunday', hint: 'vaskresenye' },
    { id: 'nedelya', lemma: 'неделя', translation: 'week', hint: 'nedyelya' },
    { id: 'kak', lemma: 'как', translation: 'how' },
    { id: 'pochemu', lemma: 'почему', translation: 'why', hint: 'pachemu' },
    { id: 'kakoy', lemma: 'какой', translation: 'which / what kind', hint: 'kakoy' },
    // Unit 8 — food & shopping
    { id: 'myaso', lemma: 'мясо', translation: 'meat', hint: 'myasa' },
    { id: 'ryba', lemma: 'рыба', translation: 'fish' },
    { id: 'frukty', lemma: 'фрукты', translation: 'fruit', hint: 'frukty' },
    { id: 'ovoshchi', lemma: 'овощи', translation: 'vegetables', hint: 'ovashchi' },
    { id: 'sakhar', lemma: 'сахар', translation: 'sugar', hint: 'sakhar' },
    { id: 'sol', lemma: 'соль', translation: 'salt', hint: 'sol' },
    { id: 'yaytso', lemma: 'яйцо', translation: 'egg', hint: 'yaytso' },
    { id: 'kupit', lemma: 'купить', translation: 'to buy', forms: ['куплю', 'купи'], hint: 'kupit' },
    { id: 'stoit', lemma: 'стоит', translation: 'costs', hint: 'stoit' },
    { id: 'dorogo', lemma: 'дорого', translation: 'expensive', hint: 'doraga' },
    { id: 'deshevo', lemma: 'дёшево', translation: 'cheap', hint: 'dyosheva' },
    // Unit 9 — action verbs
    { id: 'idti', lemma: 'идти', translation: 'to go (on foot)', forms: ['иду', 'идёшь', 'идёт'], hint: 'idu (I go)' },
    { id: 'est-eat', lemma: 'есть (кушать)', translation: 'to eat', forms: ['ем', 'ешь', 'ест'], hint: 'yem (I eat)' },
    { id: 'pit', lemma: 'пить', translation: 'to drink', forms: ['пью', 'пьёшь', 'пьёт'], hint: 'pyu (I drink)' },
    { id: 'videt', lemma: 'видеть', translation: 'to see', forms: ['вижу', 'видишь', 'видит'], hint: 'vizhu (I see)' },
    { id: 'delat', lemma: 'делать', translation: 'to do / to make', forms: ['делаю', 'делаешь', 'делает'], hint: 'dyelayu (I do)' },
    { id: 'dumat', lemma: 'думать', translation: 'to think', forms: ['думаю', 'думаешь', 'думает'], hint: 'dumayu (I think)' },
    { id: 'spat', lemma: 'спать', translation: 'to sleep', forms: ['сплю', 'спишь', 'спит'], hint: 'splyu (I sleep)' },
    { id: 'park', lemma: 'парк', translation: 'park' },
    // Unit 10 — weather & feelings
    { id: 'pogoda', lemma: 'погода', translation: 'weather', hint: 'pagoda' },
    { id: 'kholodno', lemma: 'холодно', translation: 'cold', hint: 'kholadna' },
    { id: 'zharko', lemma: 'жарко', translation: 'hot', hint: 'zharka' },
    { id: 'dozhd', lemma: 'дождь', translation: 'rain', hint: 'dozhd' },
    { id: 'sneg', lemma: 'снег', translation: 'snow', hint: 'snyek' },
    { id: 'solntse', lemma: 'солнце', translation: 'sun', hint: 'sontse' },
    { id: 'ustal', lemma: 'устал', translation: 'tired (m.)', forms: ['устала'], hint: 'ustal' },
    { id: 'rad', lemma: 'рад', translation: 'glad (m.)', forms: ['рада'], hint: 'rat' },
    { id: 'mne', lemma: 'мне', translation: 'to me / I feel', hint: 'mnye' },
    // Unit 11 (A2) — past/future tense, prepositional/dative/genitive, family, jobs
    { id: 'vchera', lemma: 'вчера', translation: 'yesterday', hint: 'vchera' },
    { id: 'byl', lemma: 'был', translation: 'was (m.)', forms: ['была', 'было', 'были'], hint: 'byl' },
    { id: 'budu', lemma: 'буду', translation: 'will be / I will', forms: ['будешь', 'будет'], hint: 'budu' },
    { id: 'potom', lemma: 'потом', translation: 'then / afterwards', hint: 'patom' },
    { id: 'chitat', lemma: 'читать', translation: 'to read', forms: ['читаю', 'читаешь', 'читает', 'читал'], hint: 'chitat' },
    { id: 'pisat', lemma: 'писать', translation: 'to write', forms: ['пишу', 'пишешь', 'пишет', 'писал'], hint: 'pisat' },
    { id: 'smotret', lemma: 'смотреть', translation: 'to watch', forms: ['смотрю', 'смотришь', 'смотрит', 'смотрел'], hint: 'smatryet' },
    { id: 'slushat', lemma: 'слушать', translation: 'to listen', forms: ['слушаю', 'слушаешь', 'слушает'], hint: 'slushat' },
    { id: 'igrat', lemma: 'играть', translation: 'to play', forms: ['играю', 'играешь', 'играет'], hint: 'igrat' },
    { id: 'uchit', lemma: 'учить', translation: 'to learn / to study', forms: ['учу', 'учишь', 'учит'], hint: 'uchit' },
    { id: 'film', lemma: 'фильм', translation: 'movie', hint: "fil'm" },
    { id: 'muzyka', lemma: 'музыка', translation: 'music', forms: ['музыку'], hint: 'muzyka' },
    { id: 'o', lemma: 'о', translation: 'about', hint: 'o' },
    { id: 'mir', lemma: 'мир', translation: 'world / peace', hint: 'mir' },
    { id: 'strana', lemma: 'страна', translation: 'country', hint: 'strana' },
    { id: 'yug', lemma: 'юг', translation: 'south', hint: 'yuk' },
    { id: 'sever', lemma: 'север', translation: 'north', hint: 'syever' },
    { id: 'reka', lemma: 'река', translation: 'river', hint: 'ryeka' },
    { id: 'gora', lemma: 'гора', translation: 'mountain', hint: 'gara' },
    { id: 'nravitsya', lemma: 'нравится', translation: 'pleases (мне нравится = I like)', hint: 'nravitsya' },
    { id: 'tebe', lemma: 'тебе', translation: 'to you (informal)', hint: 'tyebye' },
    { id: 'emu', lemma: 'ему', translation: 'to him', hint: 'yemu' },
    { id: 'ey', lemma: 'ей', translation: 'to her', hint: 'yey' },
    { id: 'god', lemma: 'год', translation: 'year', forms: ['года', 'лет'], hint: 'got' },
    { id: 'vrach', lemma: 'врач', translation: 'doctor', hint: 'vrach' },
    { id: 'uchitel', lemma: 'учитель', translation: 'teacher', hint: 'uchityel' },
    { id: 'inzhener', lemma: 'инженер', translation: 'engineer', hint: 'inzhenyer' },
    { id: 'direktor', lemma: 'директор', translation: 'director / boss', hint: 'direktar' },
    { id: 'zhena', lemma: 'жена', translation: 'wife', hint: 'zhena' },
    { id: 'muzh', lemma: 'муж', translation: 'husband', hint: 'muzh' },
    { id: 'deti', lemma: 'дети', translation: 'children', hint: 'dyeti' },
    { id: 'babushka', lemma: 'бабушка', translation: 'grandmother', hint: 'babushka' },
    { id: 'dedushka', lemma: 'дедушка', translation: 'grandfather', hint: 'dyedushka' },
    { id: 'syn', lemma: 'сын', translation: 'son', hint: 'syn' },
    { id: 'doch', lemma: 'дочь', translation: 'daughter', hint: 'doch' },
    { id: 'u-menya-net', lemma: 'у меня нет', translation: "I don't have", hint: 'u menya nyet' },
    { id: 'vremya', lemma: 'время', translation: 'time', forms: ['времени'], hint: 'vryemya' },
    { id: 'rynok', lemma: 'рынок', translation: 'market', hint: 'rynak' },
    { id: 'tsena', lemma: 'цена', translation: 'price', hint: 'tsyena' },
    { id: 'rubl', lemma: 'рубль', translation: 'ruble', forms: ['рублей'], hint: 'rubl' },
    { id: 'nuzhno', lemma: 'нужно', translation: 'necessary / need to', hint: 'nuzhna' },
    { id: 'idi', lemma: 'иди', translation: 'go! (imperative)', hint: 'idi' },
    { id: 'posmotri', lemma: 'посмотри', translation: 'look! (imperative)', hint: 'pasmatri' },
    { id: 'skazhi', lemma: 'скажи', translation: 'tell/say! (imperative)', hint: 'skazhi' },
    // Unit 12 (B1) — instrumental case, verb aspect, motion verbs with prefixes
    { id: 'moy', lemma: 'мой', translation: 'my', forms: ['моя', 'моё', 'мои'], hint: 'moy' },
    { id: 's-with', lemma: 'с', translation: 'with (+instrumental)', hint: 's' },
    { id: 'kem', lemma: 'кем', translation: 'whom (instrumental)', hint: 'kyem' },
    { id: 'prochitat', lemma: 'прочитать', translation: 'to read (perfective)', forms: ['прочитал', 'прочитала'], hint: 'prachitat' },
    { id: 'napisat', lemma: 'написать', translation: 'to write (perfective)', forms: ['написал', 'написала'], hint: 'napisat' },
    { id: 'posmotret-pf', lemma: 'посмотреть', translation: 'to watch (perfective)', forms: ['посмотрел', 'посмотрела'], hint: 'pasmatryet' },
    { id: 'poyti', lemma: 'пойти', translation: 'to set off (perfective, on foot)', forms: ['пошёл', 'пошла'], hint: 'payti' },
    { id: 'priyti', lemma: 'прийти', translation: 'to arrive (perfective, on foot)', forms: ['пришёл', 'пришла'], hint: 'priyti' },
    { id: 'uyti', lemma: 'уйти', translation: 'to leave (perfective, on foot)', forms: ['ушёл', 'ушла'], hint: 'uyti' },
    { id: 'domoy', lemma: 'домой', translation: 'home (homeward)', hint: 'damoy' },
    { id: 'kuda', lemma: 'куда', translation: 'where to', hint: 'kuda' },
    // Unit 13 (B2) — conditional mood, participles, чтобы-clauses, passive voice
    { id: 'esli', lemma: 'если', translation: 'if', hint: 'yesli' },
    { id: 'by', lemma: 'бы', translation: '(conditional particle) would', hint: 'by' },
    { id: 'chtoby', lemma: 'чтобы', translation: 'in order to / so that', hint: 'chtoby' },
    { id: 'potomu-chto', lemma: 'потому что', translation: 'because', hint: 'patamu shto' },
    { id: 'rabotayushchiy', lemma: 'работающий', translation: 'working (active participle)', forms: ['работающего', 'работающая'], hint: 'rabotayushchiy' },
    { id: 'chitayushchiy', lemma: 'читающий', translation: 'reading (active participle)', forms: ['читающего', 'читающая'], hint: 'chitayushchiy' },
    { id: 'otkryt', lemma: 'открыт', translation: 'open / opened (passive)', forms: ['открыта', 'открыто'], hint: 'atkryt' },
    { id: 'zakryt', lemma: 'закрыт', translation: 'closed (passive)', forms: ['закрыта', 'закрыто'], hint: 'zakryt' },
    { id: 'sdelano', lemma: 'сделано', translation: 'done / made (passive)', hint: 'sdyelana' },
  ],
  patterns: [
    {
      id: 'chto-eto',
      frame: 'Что это?',
      frameTranslation: 'What is this?',
      slots: [],
    },
    {
      id: 'eto-x',
      frame: 'Это ___',
      frameTranslation: 'This is ___',
      slots: [
        { vocabId: 'voda', form: 'вода', translation: 'water' },
        { vocabId: 'kot', form: 'кот', translation: 'a cat' },
        { vocabId: 'dom', form: 'дом', translation: 'a house' },
        { vocabId: 'kniga', form: 'книга', translation: 'a book' },
        { vocabId: 'mama', form: 'мама', translation: 'mom' },
      ],
    },
    {
      id: 'ya-khochu-x',
      frame: 'Я хочу ___',
      frameTranslation: 'I want ___',
      slots: [
        { vocabId: 'chay', form: 'чай', translation: 'tea' },
        { vocabId: 'kofe', form: 'кофе', translation: 'coffee' },
        { vocabId: 'voda', form: 'воду', translation: 'water' },
        { vocabId: 'sok', form: 'сок', translation: 'juice' },
        { vocabId: 'khleb', form: 'хлеб', translation: 'bread' },
        { vocabId: 'sup', form: 'суп', translation: 'soup' },
      ],
    },
    {
      id: 'u-menya-est-x',
      frame: 'У меня есть ___',
      frameTranslation: 'I have ___',
      slots: [
        { vocabId: 'kot', form: 'кот', translation: 'a cat' },
        { vocabId: 'sobaka', form: 'собака', translation: 'a dog' },
        { vocabId: 'kniga', form: 'книга', translation: 'a book' },
        { vocabId: 'telefon', form: 'телефон', translation: 'a phone' },
        { vocabId: 'dengi', form: 'деньги', translation: 'money' },
      ],
    },
    {
      id: 'mozhno-x',
      frame: 'Можно ___?',
      frameTranslation: 'May I have ___?',
      slots: [
        { vocabId: 'chay', form: 'чай', translation: 'tea' },
        { vocabId: 'kofe', form: 'кофе', translation: 'coffee' },
        { vocabId: 'moloko', form: 'молоко', translation: 'milk' },
        { vocabId: 'syr', form: 'сыр', translation: 'cheese' },
      ],
    },
    {
      id: 'ya-lyublyu-x',
      frame: 'Я люблю ___',
      frameTranslation: 'I love ___',
      slots: [
        { vocabId: 'mama', form: 'маму', translation: 'mom' },
        { vocabId: 'chay', form: 'чай', translation: 'tea' },
        { vocabId: 'sobaka', form: 'собаку', translation: 'the dog' },
        { vocabId: 'rossiya', form: 'Россию', translation: 'Russia' },
      ],
    },
    {
      id: 'gde-x',
      frame: 'Где ___?',
      frameTranslation: 'Where is ___?',
      slots: [
        { vocabId: 'tualet', form: 'туалет', translation: 'the toilet' },
        { vocabId: 'metro', form: 'метро', translation: 'the metro' },
        { vocabId: 'vokzal', form: 'вокзал', translation: 'the train station' },
        { vocabId: 'magazin', form: 'магазин', translation: 'the shop' },
        { vocabId: 'restoran', form: 'ресторан', translation: 'the restaurant' },
      ],
    },
    {
      id: 'ya-zhivu-v-x',
      frame: 'Я живу в ___',
      frameTranslation: 'I live in ___',
      slots: [
        { vocabId: 'moskva', form: 'Москве', translation: 'Moscow' },
        { vocabId: 'rossiya', form: 'России', translation: 'Russia' },
        { vocabId: 'gorod', form: 'городе', translation: 'the city' },
        { vocabId: 'dom', form: 'доме', translation: 'the house' },
      ],
    },
    {
      id: 'eto-ochen-x',
      frame: 'Это очень ___',
      frameTranslation: 'This is very ___',
      slots: [
        { vocabId: 'khorosho', form: 'хорошо', translation: 'good' },
        { vocabId: 'krasivy', form: 'красиво', translation: 'beautiful' },
        { vocabId: 'vkusny', form: 'вкусно', translation: 'tasty' },
        { vocabId: 'plokho', form: 'плохо', translation: 'bad' },
        { vocabId: 'dorogo', form: 'дорого', translation: 'expensive' },
      ],
    },
    {
      id: 'skolko-stoit-x',
      frame: 'Сколько стоит ___?',
      frameTranslation: 'How much does ___ cost?',
      slots: [
        { vocabId: 'khleb', form: 'хлеб', translation: 'the bread' },
        { vocabId: 'syr', form: 'сыр', translation: 'the cheese' },
        { vocabId: 'kofe', form: 'кофе', translation: 'the coffee' },
        { vocabId: 'kniga', form: 'книга', translation: 'the book' },
        { vocabId: 'ryba', form: 'рыба', translation: 'the fish' },
      ],
    },
    {
      id: 'ya-idu-v-x',
      frame: 'Я иду в ___',
      frameTranslation: 'I am going to ___',
      slots: [
        { vocabId: 'magazin', form: 'магазин', translation: 'the shop' },
        { vocabId: 'shkola', form: 'школу', translation: 'school' },
        { vocabId: 'restoran', form: 'ресторан', translation: 'the restaurant' },
        { vocabId: 'park', form: 'парк', translation: 'the park' },
      ],
    },
    {
      id: 'mne-x',
      frame: 'Мне ___',
      frameTranslation: 'I feel ___',
      slots: [
        { vocabId: 'kholodno', form: 'холодно', translation: 'cold' },
        { vocabId: 'zharko', form: 'жарко', translation: 'hot' },
        { vocabId: 'khorosho', form: 'хорошо', translation: 'good' },
        { vocabId: 'plokho', form: 'плохо', translation: 'bad' },
      ],
    },
    {
      id: 'budu-x',
      frame: 'Завтра я буду ___',
      frameTranslation: 'Tomorrow I will ___',
      slots: [
        { vocabId: 'chitat', form: 'читать', translation: 'read' },
        { vocabId: 'pisat', form: 'писать', translation: 'write' },
        { vocabId: 'smotret', form: 'смотреть', translation: 'watch' },
        { vocabId: 'igrat', form: 'играть', translation: 'play' },
      ],
    },
    {
      id: 'mne-nravitsya-x',
      frame: 'Мне нравится ___',
      frameTranslation: 'I like ___',
      slots: [
        { vocabId: 'chay', form: 'чай', translation: 'tea' },
        { vocabId: 'kofe', form: 'кофе', translation: 'coffee' },
        { vocabId: 'kniga', form: 'книга', translation: 'this book' },
        { vocabId: 'rabota', form: 'работа', translation: 'this job' },
      ],
    },
    {
      id: 'u-menya-net-x',
      frame: 'У меня нет ___',
      frameTranslation: 'I do not have ___',
      slots: [
        { vocabId: 'vremya', form: 'времени', translation: 'time' },
        { vocabId: 'dengi', form: 'денег', translation: 'money' },
        { vocabId: 'telefon', form: 'телефона', translation: 'a phone' },
        { vocabId: 'kot', form: 'кота', translation: 'a cat' },
      ],
    },
    {
      id: 'rabotayu-x',
      frame: 'Я работаю ___',
      frameTranslation: 'I work as ___',
      slots: [
        { vocabId: 'vrach', form: 'врачом', translation: 'a doctor' },
        { vocabId: 'uchitel', form: 'учителем', translation: 'a teacher' },
        { vocabId: 'inzhener', form: 'инженером', translation: 'an engineer' },
        { vocabId: 'direktor', form: 'директором', translation: 'a director' },
      ],
    },
  ],
  units: [
    {
      id: 'u1',
      title: 'Survival patterns',
      description: 'Greetings, yes/no, and your first sentences',
      level: 'A1',
      skills: [
        {
          id: 'u1s1',
          title: 'Hello & thanks',
          icon: 'hand',
          lessons: [
            {
              id: 'u1s1l1',
              title: 'First words',
              vocabIds: ['privet', 'poka', 'da', 'net', 'spasibo'],
              sentences: [
                { text: 'Привет!', translation: 'Hi!', vocabIds: ['privet'] },
                { text: 'Да, спасибо.', translation: 'Yes, thank you.', vocabIds: ['da', 'spasibo'] },
                { text: 'Нет, спасибо.', translation: 'No, thank you.', vocabIds: ['net', 'spasibo'] },
                { text: 'Пока!', translation: 'Bye!', vocabIds: ['poka'] },
              ],
            },
            {
              id: 'u1s1l2',
              title: 'Being polite',
              vocabIds: ['zdravstvuyte', 'do-svidaniya', 'pozhaluysta', 'izvinite'],
              sentences: [
                { text: 'Здравствуйте!', translation: 'Hello!', vocabIds: ['zdravstvuyte'] },
                { text: 'Извините, пожалуйста.', translation: 'Excuse me, please.', vocabIds: ['izvinite', 'pozhaluysta'] },
                { text: 'Спасибо! — Пожалуйста.', translation: 'Thank you! — You are welcome.', vocabIds: ['spasibo', 'pozhaluysta'] },
                { text: 'До свидания!', translation: 'Goodbye!', vocabIds: ['do-svidaniya'] },
              ],
            },
          ],
        },
        {
          id: 'u1s2',
          title: 'This is…',
          icon: 'sparkles',
          lessons: [
            {
              id: 'u1s2l1',
              title: 'What is this?',
              vocabIds: ['eto', 'chto', 'kto', 'ya', 'ty'],
              patternIds: ['chto-eto', 'eto-x'],
              sentences: [
                { text: 'Что это?', translation: 'What is this?', vocabIds: ['chto', 'eto'] },
                { text: 'Это дом.', translation: 'This is a house.', vocabIds: ['eto', 'dom'] },
                { text: 'Кто это?', translation: 'Who is this?', vocabIds: ['kto', 'eto'] },
                { text: 'Это я!', translation: 'It is me!', vocabIds: ['eto', 'ya'] },
              ],
            },
            {
              id: 'u1s2l2',
              title: 'Good & bad',
              vocabIds: ['khorosho', 'plokho', 'ochen', 'vy'],
              sentences: [
                { text: 'Очень хорошо!', translation: 'Very good!', vocabIds: ['ochen', 'khorosho'] },
                { text: 'Это плохо.', translation: 'This is bad.', vocabIds: ['eto', 'plokho'] },
                { text: 'Как вы?', translation: 'How are you?', vocabIds: ['vy'] },
                { text: 'Хорошо, спасибо!', translation: 'Good, thanks!', vocabIds: ['khorosho', 'spasibo'] },
              ],
            },
          ],
        },
      ],
    },
    {
      id: 'u2',
      title: 'I want / I have',
      description: 'Order food and talk about what you own',
      level: 'A1',
      skills: [
        {
          id: 'u2s1',
          title: 'I want…',
          icon: 'coffee',
          lessons: [
            {
              id: 'u2s1l1',
              title: 'Drinks',
              vocabIds: ['khochu', 'voda', 'chay', 'kofe', 'sok'],
              patternIds: ['ya-khochu-x'],
              sentences: [
                { text: 'Я хочу чай.', translation: 'I want tea.', vocabIds: ['khochu', 'chay'] },
                { text: 'Я хочу кофе.', translation: 'I want coffee.', vocabIds: ['khochu', 'kofe'] },
                { text: 'Я хочу воду, пожалуйста.', translation: 'I want water, please.', vocabIds: ['khochu', 'voda', 'pozhaluysta'] },
              ],
            },
            {
              id: 'u2s1l2',
              title: 'Food',
              vocabIds: ['khleb', 'moloko', 'syr', 'yabloko', 'sup', 'mozhno'],
              patternIds: ['mozhno-x'],
              sentences: [
                { text: 'Можно хлеб?', translation: 'May I have bread?', vocabIds: ['mozhno', 'khleb'] },
                { text: 'Я хочу суп и сыр.', translation: 'I want soup and cheese.', vocabIds: ['khochu', 'sup', 'syr'] },
                { text: 'Это молоко.', translation: 'This is milk.', vocabIds: ['eto', 'moloko'] },
                { text: 'Можно яблоко, пожалуйста?', translation: 'May I have an apple, please?', vocabIds: ['mozhno', 'yabloko', 'pozhaluysta'] },
              ],
            },
          ],
        },
        {
          id: 'u2s2',
          title: 'I have…',
          icon: 'package',
          lessons: [
            {
              id: 'u2s2l1',
              title: 'My things',
              vocabIds: ['u-menya-est', 'dom', 'kot', 'sobaka', 'kniga'],
              patternIds: ['u-menya-est-x'],
              sentences: [
                { text: 'У меня есть кот.', translation: 'I have a cat.', vocabIds: ['u-menya-est', 'kot'] },
                { text: 'У меня есть дом.', translation: 'I have a house.', vocabIds: ['u-menya-est', 'dom'] },
                { text: 'У меня есть собака и кот.', translation: 'I have a dog and a cat.', vocabIds: ['u-menya-est', 'sobaka', 'kot'] },
              ],
            },
            {
              id: 'u2s2l2',
              title: 'Phone & money',
              vocabIds: ['telefon', 'dengi'],
              sentences: [
                { text: 'У меня есть телефон.', translation: 'I have a phone.', vocabIds: ['u-menya-est', 'telefon'] },
                { text: 'У меня есть деньги.', translation: 'I have money.', vocabIds: ['u-menya-est', 'dengi'] },
                { text: 'Это телефон? Да!', translation: 'Is this a phone? Yes!', vocabIds: ['eto', 'telefon', 'da'] },
              ],
            },
          ],
        },
      ],
    },
    {
      id: 'u3',
      title: 'People & verbs',
      description: 'Family, friends, and your first verbs',
      level: 'A1',
      skills: [
        {
          id: 'u3s1',
          title: 'Family',
          icon: 'users',
          lessons: [
            {
              id: 'u3s1l1',
              title: 'Mom & dad',
              vocabIds: ['mama', 'papa', 'brat', 'sestra', 'on', 'ona'],
              sentences: [
                { text: 'Это мама и папа.', translation: 'This is mom and dad.', vocabIds: ['eto', 'mama', 'papa'] },
                { text: 'Он брат, она сестра.', translation: 'He is a brother, she is a sister.', vocabIds: ['on', 'brat', 'ona', 'sestra'] },
                { text: 'У меня есть брат.', translation: 'I have a brother.', vocabIds: ['u-menya-est', 'brat'] },
              ],
            },
            {
              id: 'u3s1l2',
              title: 'Friends & people',
              vocabIds: ['drug', 'chelovek', 'my', 'oni', 'lyublyu'],
              patternIds: ['ya-lyublyu-x'],
              sentences: [
                { text: 'Он мой друг.', translation: 'He is my friend.', vocabIds: ['on', 'drug'] },
                { text: 'Я люблю маму.', translation: 'I love mom.', vocabIds: ['lyublyu', 'mama'] },
                { text: 'Мы и они.', translation: 'We and they.', vocabIds: ['my', 'oni'] },
              ],
            },
          ],
        },
        {
          id: 'u3s2',
          title: 'First verbs',
          icon: 'message-circle',
          lessons: [
            {
              id: 'u3s2l1',
              title: 'Speak & understand',
              vocabIds: ['govoryu', 'ponimayu', 'znayu', 'po-russki', 'po-angliyski'],
              sentences: [
                { text: 'Я говорю по-русски.', translation: 'I speak Russian.', vocabIds: ['govoryu', 'po-russki'] },
                { text: 'Я не понимаю.', translation: 'I do not understand.', vocabIds: ['ponimayu'] },
                { text: 'Вы говорите по-английски?', translation: 'Do you speak English?', vocabIds: ['vy', 'govoryu', 'po-angliyski'] },
                { text: 'Я знаю.', translation: 'I know.', vocabIds: ['znayu'] },
              ],
            },
            {
              id: 'u3s2l2',
              title: 'Live & work',
              vocabIds: ['zhivu', 'rabotayu'],
              sentences: [
                { text: 'Я живу здесь.', translation: 'I live here.', vocabIds: ['zhivu', 'zdes'] },
                { text: 'Она работает.', translation: 'She works.', vocabIds: ['ona', 'rabotayu'] },
                { text: 'Я работаю дома.', translation: 'I work at home.', vocabIds: ['rabotayu', 'dom'] },
              ],
            },
          ],
        },
      ],
    },
    {
      id: 'u4',
      title: 'Places',
      description: 'Ask where things are and say where you live',
      level: 'A1',
      skills: [
        {
          id: 'u4s1',
          title: 'Where is…?',
          icon: 'map-pin',
          lessons: [
            {
              id: 'u4s1l1',
              title: 'Here & there',
              vocabIds: ['gde', 'zdes', 'tam', 'tualet', 'metro'],
              patternIds: ['gde-x'],
              sentences: [
                { text: 'Где туалет?', translation: 'Where is the toilet?', vocabIds: ['gde', 'tualet'] },
                { text: 'Метро там.', translation: 'The metro is there.', vocabIds: ['metro', 'tam'] },
                { text: 'Я здесь!', translation: 'I am here!', vocabIds: ['ya', 'zdes'] },
              ],
            },
            {
              id: 'u4s1l2',
              title: 'Around town',
              vocabIds: ['magazin', 'vokzal', 'restoran', 'ulitsa'],
              sentences: [
                { text: 'Где магазин?', translation: 'Where is the shop?', vocabIds: ['gde', 'magazin'] },
                { text: 'Вокзал здесь, ресторан там.', translation: 'The station is here, the restaurant is there.', vocabIds: ['vokzal', 'zdes', 'restoran', 'tam'] },
                { text: 'Это улица.', translation: 'This is a street.', vocabIds: ['eto', 'ulitsa'] },
              ],
            },
          ],
        },
        {
          id: 'u4s2',
          title: 'I live in…',
          icon: 'home',
          lessons: [
            {
              id: 'u4s2l1',
              title: 'City life',
              vocabIds: ['gorod', 'moskva', 'rossiya', 'shkola', 'rabota'],
              patternIds: ['ya-zhivu-v-x'],
              sentences: [
                { text: 'Я живу в Москве.', translation: 'I live in Moscow.', vocabIds: ['zhivu', 'moskva'] },
                { text: 'Москва — это город в России.', translation: 'Moscow is a city in Russia.', vocabIds: ['moskva', 'eto', 'gorod', 'rossiya'] },
                { text: 'Школа там.', translation: 'The school is there.', vocabIds: ['shkola', 'tam'] },
              ],
            },
          ],
        },
      ],
    },
    {
      id: 'u5',
      title: 'Numbers & time',
      description: 'Count to ten and talk about your day',
      level: 'A1',
      skills: [
        {
          id: 'u5s1',
          title: 'One to ten',
          icon: 'hash',
          lessons: [
            {
              id: 'u5s1l1',
              title: '1–5',
              vocabIds: ['odin', 'dva', 'tri', 'chetyre', 'pyat'],
              sentences: [
                { text: 'Один, два, три.', translation: 'One, two, three.', vocabIds: ['odin', 'dva', 'tri'] },
                { text: 'Четыре и пять.', translation: 'Four and five.', vocabIds: ['chetyre', 'pyat'] },
                { text: 'У меня есть два кота.', translation: 'I have two cats.', vocabIds: ['u-menya-est', 'dva', 'kot'] },
              ],
            },
            {
              id: 'u5s1l2',
              title: '6–10',
              vocabIds: ['shest', 'sem', 'vosem', 'devyat', 'desyat'],
              sentences: [
                { text: 'Шесть, семь, восемь.', translation: 'Six, seven, eight.', vocabIds: ['shest', 'sem', 'vosem'] },
                { text: 'Девять и десять.', translation: 'Nine and ten.', vocabIds: ['devyat', 'desyat'] },
              ],
            },
          ],
        },
        {
          id: 'u5s2',
          title: 'My day',
          icon: 'clock',
          lessons: [
            {
              id: 'u5s2l1',
              title: 'Times of day',
              vocabIds: ['utro', 'den', 'vecher', 'noch', 'chas'],
              sentences: [
                { text: 'Утро, день, вечер, ночь.', translation: 'Morning, day, evening, night.', vocabIds: ['utro', 'den', 'vecher', 'noch'] },
                { text: 'Сейчас час.', translation: 'It is one o’clock now.', vocabIds: ['seychas', 'chas'] },
              ],
            },
            {
              id: 'u5s2l2',
              title: 'Today & tomorrow',
              vocabIds: ['segodnya', 'zavtra', 'seychas', 'kogda', 'skolko'],
              sentences: [
                { text: 'Когда? Сегодня или завтра?', translation: 'When? Today or tomorrow?', vocabIds: ['kogda', 'segodnya', 'zavtra'] },
                { text: 'Сейчас!', translation: 'Now!', vocabIds: ['seychas'] },
                { text: 'Сколько это?', translation: 'How much is this?', vocabIds: ['skolko', 'eto'] },
              ],
            },
          ],
        },
      ],
    },
    {
      id: 'u6',
      title: 'Describing things',
      description: 'Colors and your first adjectives',
      level: 'A1',
      skills: [
        {
          id: 'u6s1',
          title: 'Colors',
          icon: 'sparkles',
          lessons: [
            {
              id: 'u6s1l1',
              title: 'Red, blue, green',
              vocabIds: ['krasny', 'siniy', 'zelyony'],
              sentences: [
                { text: 'Это красный дом.', translation: 'This is a red house.', vocabIds: ['eto', 'krasny', 'dom'] },
                { text: 'Кот синий? Нет!', translation: 'Is the cat blue? No!', vocabIds: ['kot', 'siniy', 'net'] },
                { text: 'Парк зелёный.', translation: 'The park is green.', vocabIds: ['park', 'zelyony'] },
              ],
            },
            {
              id: 'u6s1l2',
              title: 'Yellow, black, white',
              vocabIds: ['zholty', 'cherny', 'bely'],
              sentences: [
                { text: 'Солнце жёлтое.', translation: 'The sun is yellow.', vocabIds: ['solntse', 'zholty'] },
                { text: 'Чёрный кот и белая собака.', translation: 'A black cat and a white dog.', vocabIds: ['cherny', 'kot', 'bely', 'sobaka'] },
                { text: 'Снег белый.', translation: 'Snow is white.', vocabIds: ['sneg', 'bely'] },
              ],
            },
          ],
        },
        {
          id: 'u6s2',
          title: 'Big & small',
          icon: 'package',
          lessons: [
            {
              id: 'u6s2l1',
              title: 'Size & age',
              vocabIds: ['bolshoy', 'malenkiy', 'novy', 'stary'],
              sentences: [
                { text: 'Это большой город.', translation: 'This is a big city.', vocabIds: ['eto', 'bolshoy', 'gorod'] },
                { text: 'Маленький кот, большая собака.', translation: 'A small cat, a big dog.', vocabIds: ['malenkiy', 'kot', 'bolshoy', 'sobaka'] },
                { text: 'У меня есть новый телефон.', translation: 'I have a new phone.', vocabIds: ['u-menya-est', 'novy', 'telefon'] },
                { text: 'Это старый дом.', translation: 'This is an old house.', vocabIds: ['eto', 'stary', 'dom'] },
              ],
            },
            {
              id: 'u6s2l2',
              title: 'Beautiful & tasty',
              vocabIds: ['krasivy', 'vkusny'],
              patternIds: ['eto-ochen-x'],
              sentences: [
                { text: 'Москва — красивый город.', translation: 'Moscow is a beautiful city.', vocabIds: ['moskva', 'krasivy', 'gorod'] },
                { text: 'Суп очень вкусный!', translation: 'The soup is very tasty!', vocabIds: ['sup', 'ochen', 'vkusny'] },
                { text: 'Это очень красиво.', translation: 'This is very beautiful.', vocabIds: ['eto', 'ochen', 'krasivy'] },
              ],
            },
          ],
        },
      ],
    },
    {
      id: 'u7',
      title: 'Days & questions',
      description: 'The week and how to ask about anything',
      level: 'A1',
      skills: [
        {
          id: 'u7s1',
          title: 'Days of the week',
          icon: 'clock',
          lessons: [
            {
              id: 'u7s1l1',
              title: 'Monday to Thursday',
              vocabIds: ['ponedelnik', 'vtornik', 'sreda', 'chetverg'],
              sentences: [
                { text: 'Сегодня понедельник.', translation: 'Today is Monday.', vocabIds: ['segodnya', 'ponedelnik'] },
                { text: 'Завтра вторник.', translation: 'Tomorrow is Tuesday.', vocabIds: ['zavtra', 'vtornik'] },
                { text: 'Среда или четверг?', translation: 'Wednesday or Thursday?', vocabIds: ['sreda', 'chetverg'] },
              ],
            },
            {
              id: 'u7s1l2',
              title: 'The weekend',
              vocabIds: ['pyatnitsa', 'subbota', 'voskresene', 'nedelya'],
              sentences: [
                { text: 'Я люблю пятницу!', translation: 'I love Friday!', vocabIds: ['lyublyu', 'pyatnitsa'] },
                { text: 'Суббота и воскресенье.', translation: 'Saturday and Sunday.', vocabIds: ['subbota', 'voskresene'] },
                { text: 'Неделя — это семь дней.', translation: 'A week is seven days.', vocabIds: ['nedelya', 'eto', 'sem', 'den'] },
              ],
            },
          ],
        },
        {
          id: 'u7s2',
          title: 'Asking questions',
          icon: 'message-circle',
          lessons: [
            {
              id: 'u7s2l1',
              title: 'How, why, which',
              vocabIds: ['kak', 'pochemu', 'kakoy'],
              sentences: [
                { text: 'Как вы?', translation: 'How are you?', vocabIds: ['kak', 'vy'] },
                { text: 'Почему нет?', translation: 'Why not?', vocabIds: ['pochemu', 'net'] },
                { text: 'Какой сегодня день?', translation: 'What day is it today?', vocabIds: ['kakoy', 'segodnya', 'den'] },
                { text: 'Какой это цвет? Красный.', translation: 'What color is this? Red.', vocabIds: ['kakoy', 'eto', 'krasny'] },
              ],
            },
          ],
        },
      ],
    },
    {
      id: 'u8',
      title: 'Food & shopping',
      description: 'Buy food and ask prices like a local',
      level: 'A1',
      skills: [
        {
          id: 'u8s1',
          title: 'More food',
          icon: 'coffee',
          lessons: [
            {
              id: 'u8s1l1',
              title: 'Meat & fish',
              vocabIds: ['myaso', 'ryba', 'yaytso', 'est-eat'],
              sentences: [
                { text: 'Я ем мясо и рыбу.', translation: 'I eat meat and fish.', vocabIds: ['est-eat', 'myaso', 'ryba'] },
                { text: 'Это яйцо.', translation: 'This is an egg.', vocabIds: ['eto', 'yaytso'] },
                { text: 'Ты ешь рыбу?', translation: 'Do you eat fish?', vocabIds: ['ty', 'est-eat', 'ryba'] },
              ],
            },
            {
              id: 'u8s1l2',
              title: 'Fruit & veg',
              vocabIds: ['frukty', 'ovoshchi', 'sakhar', 'sol'],
              sentences: [
                { text: 'Фрукты и овощи — это хорошо.', translation: 'Fruit and vegetables are good.', vocabIds: ['frukty', 'ovoshchi', 'eto', 'khorosho'] },
                { text: 'Сахар или соль?', translation: 'Sugar or salt?', vocabIds: ['sakhar', 'sol'] },
                { text: 'Я хочу фрукты.', translation: 'I want fruit.', vocabIds: ['khochu', 'frukty'] },
              ],
            },
          ],
        },
        {
          id: 'u8s2',
          title: 'How much?',
          icon: 'hash',
          lessons: [
            {
              id: 'u8s2l1',
              title: 'Prices',
              vocabIds: ['kupit', 'stoit', 'dorogo', 'deshevo'],
              patternIds: ['skolko-stoit-x'],
              sentences: [
                { text: 'Сколько стоит хлеб?', translation: 'How much does the bread cost?', vocabIds: ['skolko', 'stoit', 'khleb'] },
                { text: 'Это очень дорого!', translation: 'This is very expensive!', vocabIds: ['eto', 'ochen', 'dorogo'] },
                { text: 'Дёшево! Я хочу купить.', translation: 'Cheap! I want to buy it.', vocabIds: ['deshevo', 'khochu', 'kupit'] },
              ],
            },
          ],
        },
      ],
    },
    {
      id: 'u9',
      title: 'Action verbs',
      description: 'Go, eat, drink, see, do, think, sleep',
      level: 'A1',
      skills: [
        {
          id: 'u9s1',
          title: 'Going places',
          icon: 'map-pin',
          lessons: [
            {
              id: 'u9s1l1',
              title: 'I am going…',
              vocabIds: ['idti', 'park'],
              patternIds: ['ya-idu-v-x'],
              sentences: [
                { text: 'Я иду в магазин.', translation: 'I am going to the shop.', vocabIds: ['idti', 'magazin'] },
                { text: 'Мы идём в парк.', translation: 'We are going to the park.', vocabIds: ['my', 'idti', 'park'] },
                { text: 'Куда ты идёшь?', translation: 'Where are you going?', vocabIds: ['ty', 'idti'] },
              ],
            },
            {
              id: 'u9s1l2',
              title: 'Eat & drink',
              vocabIds: ['pit'],
              sentences: [
                { text: 'Я пью кофе.', translation: 'I drink coffee.', vocabIds: ['pit', 'kofe'] },
                { text: 'Он пьёт чай, она пьёт сок.', translation: 'He drinks tea, she drinks juice.', vocabIds: ['on', 'pit', 'chay', 'ona', 'sok'] },
                { text: 'Я ем и пью.', translation: 'I eat and drink.', vocabIds: ['est-eat', 'pit'] },
              ],
            },
          ],
        },
        {
          id: 'u9s2',
          title: 'Think & do',
          icon: 'sparkles',
          lessons: [
            {
              id: 'u9s2l1',
              title: 'See, do, think',
              vocabIds: ['videt', 'delat', 'dumat'],
              sentences: [
                { text: 'Я вижу кота.', translation: 'I see a cat.', vocabIds: ['videt', 'kot'] },
                { text: 'Что ты делаешь?', translation: 'What are you doing?', vocabIds: ['chto', 'ty', 'delat'] },
                { text: 'Я думаю, это хорошо.', translation: 'I think this is good.', vocabIds: ['dumat', 'eto', 'khorosho'] },
              ],
            },
            {
              id: 'u9s2l2',
              title: 'Sleep',
              vocabIds: ['spat'],
              sentences: [
                { text: 'Я сплю.', translation: 'I am sleeping.', vocabIds: ['spat'] },
                { text: 'Кот спит дома.', translation: 'The cat sleeps at home.', vocabIds: ['kot', 'spat', 'dom'] },
                { text: 'Ночью я сплю, утром я работаю.', translation: 'At night I sleep, in the morning I work.', vocabIds: ['noch', 'spat', 'utro', 'rabotayu'] },
              ],
            },
          ],
        },
      ],
    },
    {
      id: 'u10',
      title: 'Weather & feelings',
      description: 'Talk about the weather and how you feel',
      level: 'A1',
      skills: [
        {
          id: 'u10s1',
          title: 'Weather',
          icon: 'home',
          lessons: [
            {
              id: 'u10s1l1',
              title: 'Hot & cold',
              vocabIds: ['pogoda', 'kholodno', 'zharko', 'mne'],
              patternIds: ['mne-x'],
              sentences: [
                { text: 'Какая сегодня погода?', translation: 'What is the weather today?', vocabIds: ['kakoy', 'segodnya', 'pogoda'] },
                { text: 'Мне холодно!', translation: 'I am cold!', vocabIds: ['mne', 'kholodno'] },
                { text: 'Сегодня жарко.', translation: 'It is hot today.', vocabIds: ['segodnya', 'zharko'] },
              ],
            },
            {
              id: 'u10s1l2',
              title: 'Rain & snow',
              vocabIds: ['dozhd', 'sneg', 'solntse'],
              sentences: [
                { text: 'Дождь или снег?', translation: 'Rain or snow?', vocabIds: ['dozhd', 'sneg'] },
                { text: 'Я люблю солнце.', translation: 'I love the sun.', vocabIds: ['lyublyu', 'solntse'] },
                { text: 'Зимой снег, летом солнце.', translation: 'In winter snow, in summer sun.', vocabIds: ['sneg', 'solntse'] },
              ],
            },
          ],
        },
        {
          id: 'u10s2',
          title: 'Feelings',
          icon: 'users',
          lessons: [
            {
              id: 'u10s2l1',
              title: 'Tired & glad',
              vocabIds: ['ustal', 'rad'],
              sentences: [
                { text: 'Я устал. Я иду спать.', translation: 'I am tired. I am going to sleep.', vocabIds: ['ustal', 'idti', 'spat'] },
                { text: 'Я очень рад!', translation: 'I am very glad!', vocabIds: ['ochen', 'rad'] },
                { text: 'Мне хорошо.', translation: 'I feel good.', vocabIds: ['mne', 'khorosho'] },
              ],
            },
          ],
        },
      ],
    },
    {
      id: 'u11',
      title: 'Yesterday & tomorrow',
      description: 'Past tense, future plans, and your growing family',
      level: 'A2',
      skills: [
        {
          id: 'u11s1',
          title: 'Past tense',
          icon: 'clock',
          lessons: [
            {
              id: 'u11s1l1',
              title: 'Yesterday',
              vocabIds: ['vchera', 'byl', 'chitat', 'pisat'],
              sentences: [
                { text: 'Вчера я читал книгу.', translation: 'Yesterday I read a book.', vocabIds: ['vchera', 'chitat', 'kniga'] },
                { text: 'Вчера было холодно.', translation: 'Yesterday it was cold.', vocabIds: ['vchera', 'byl', 'kholodno'] },
                { text: 'Я писал вчера.', translation: 'I wrote yesterday.', vocabIds: ['pisat', 'vchera'] },
                { text: 'Ты был дома вчера?', translation: 'Were you home yesterday?', vocabIds: ['ty', 'byl', 'dom', 'vchera'] },
              ],
            },
            {
              id: 'u11s1l2',
              title: 'What we did',
              vocabIds: ['smotret', 'slushat', 'igrat', 'uchit', 'film', 'muzyka'],
              sentences: [
                { text: 'Я смотрел фильм.', translation: 'I watched a movie.', vocabIds: ['smotret', 'film'] },
                { text: 'Ты слушаешь музыку?', translation: 'Are you listening to music?', vocabIds: ['ty', 'slushat', 'muzyka'] },
                { text: 'Мы играем в парке.', translation: 'We play in the park.', vocabIds: ['my', 'igrat', 'park'] },
                { text: 'Я учу русский язык.', translation: 'I am learning Russian.', vocabIds: ['uchit'] },
              ],
            },
          ],
        },
        {
          id: 'u11s2',
          title: 'Future plans',
          icon: 'sparkles',
          lessons: [
            {
              id: 'u11s2l1',
              title: 'Tomorrow',
              vocabIds: ['budu', 'potom'],
              patternIds: ['budu-x'],
              sentences: [
                { text: 'Завтра я буду читать.', translation: 'Tomorrow I will read.', vocabIds: ['zavtra', 'budu', 'chitat'] },
                { text: 'Я буду работать, потом я буду спать.', translation: 'I will work, then I will sleep.', vocabIds: ['budu', 'rabotayu', 'potom', 'spat'] },
                { text: 'Что ты будешь делать завтра?', translation: 'What will you do tomorrow?', vocabIds: ['chto', 'ty', 'budu', 'delat', 'zavtra'] },
                { text: 'Завтра будет хорошо.', translation: 'Tomorrow will be good.', vocabIds: ['zavtra', 'budu', 'khorosho'] },
              ],
            },
            {
              id: 'u11s2l2',
              title: 'Needs & commands',
              vocabIds: ['nuzhno', 'idi', 'posmotri', 'skazhi'],
              sentences: [
                { text: 'Мне нужно идти.', translation: 'I need to go.', vocabIds: ['mne', 'nuzhno', 'idti'] },
                { text: 'Иди домой!', translation: 'Go home!', vocabIds: ['idi', 'dom'] },
                { text: 'Посмотри! Это кот.', translation: 'Look! It is a cat.', vocabIds: ['posmotri', 'eto', 'kot'] },
                { text: 'Скажи, пожалуйста, где метро?', translation: 'Please tell me, where is the metro?', vocabIds: ['skazhi', 'pozhaluysta', 'gde', 'metro'] },
              ],
            },
          ],
        },
        {
          id: 'u11s3',
          title: 'Country & geography',
          icon: 'map-pin',
          lessons: [
            {
              id: 'u11s3l1',
              title: 'About...',
              vocabIds: ['o', 'mir', 'strana'],
              sentences: [
                { text: 'Россия — это большая страна.', translation: 'Russia is a big country.', vocabIds: ['rossiya', 'eto', 'bolshoy', 'strana'] },
                { text: 'Я думаю о доме.', translation: 'I am thinking about home.', vocabIds: ['dumat', 'o', 'dom'] },
                { text: 'Это книга о России.', translation: 'This is a book about Russia.', vocabIds: ['eto', 'kniga', 'o', 'rossiya'] },
                { text: 'Мир большой.', translation: 'The world is big.', vocabIds: ['mir', 'bolshoy'] },
              ],
            },
            {
              id: 'u11s3l2',
              title: 'Geography',
              vocabIds: ['yug', 'sever', 'reka', 'gora'],
              sentences: [
                { text: 'На юге жарко, на севере холодно.', translation: 'In the south it is hot, in the north it is cold.', vocabIds: ['yug', 'zharko', 'sever', 'kholodno'] },
                { text: 'Это красивая река.', translation: 'This is a beautiful river.', vocabIds: ['eto', 'krasivy', 'reka'] },
                { text: 'Гора большая и красивая.', translation: 'The mountain is big and beautiful.', vocabIds: ['gora', 'bolshoy', 'krasivy'] },
                { text: 'Москва не на юге.', translation: 'Moscow is not in the south.', vocabIds: ['moskva', 'yug'] },
              ],
            },
          ],
        },
        {
          id: 'u11s4',
          title: 'Likes, age & jobs',
          icon: 'users',
          lessons: [
            {
              id: 'u11s4l1',
              title: 'I like',
              vocabIds: ['nravitsya', 'tebe', 'emu', 'ey'],
              patternIds: ['mne-nravitsya-x'],
              sentences: [
                { text: 'Мне нравится чай.', translation: 'I like tea.', vocabIds: ['mne', 'nravitsya', 'chay'] },
                { text: 'Тебе нравится кофе?', translation: 'Do you like coffee?', vocabIds: ['tebe', 'nravitsya', 'kofe'] },
                { text: 'Ему нравится работа.', translation: 'He likes the job.', vocabIds: ['emu', 'nravitsya', 'rabota'] },
                { text: 'Ей нравится книга.', translation: 'She likes the book.', vocabIds: ['ey', 'nravitsya', 'kniga'] },
              ],
            },
            {
              id: 'u11s4l2',
              title: 'Age & job',
              vocabIds: ['god', 'vrach', 'uchitel', 'inzhener', 'direktor'],
              sentences: [
                { text: 'Сколько тебе лет?', translation: 'How old are you?', vocabIds: ['skolko', 'tebe', 'god'] },
                { text: 'Мне десять лет.', translation: 'I am ten years old.', vocabIds: ['mne', 'desyat', 'god'] },
                { text: 'Она врач, а он учитель.', translation: 'She is a doctor, and he is a teacher.', vocabIds: ['ona', 'vrach', 'on', 'uchitel'] },
                { text: 'Папа — инженер. Мама — директор.', translation: 'Dad is an engineer. Mom is a director.', vocabIds: ['papa', 'inzhener', 'mama', 'direktor'] },
              ],
            },
          ],
        },
        {
          id: 'u11s5',
          title: 'Family & shopping',
          icon: 'home',
          lessons: [
            {
              id: 'u11s5l1',
              title: 'Bigger family',
              vocabIds: ['zhena', 'muzh', 'deti', 'babushka', 'dedushka', 'syn', 'doch'],
              sentences: [
                { text: 'Это моя жена, а это мой муж.', translation: 'This is my wife, and this is my husband.', vocabIds: ['eto', 'zhena', 'muzh'] },
                { text: 'У меня есть сын и дочь.', translation: 'I have a son and a daughter.', vocabIds: ['u-menya-est', 'syn', 'doch'] },
                { text: 'Бабушка и дедушка живут здесь.', translation: 'Grandma and grandpa live here.', vocabIds: ['babushka', 'dedushka', 'zhivu', 'zdes'] },
                { text: 'Дети играют.', translation: 'The children are playing.', vocabIds: ['deti', 'igrat'] },
              ],
            },
            {
              id: 'u11s5l2',
              title: 'No money, no time',
              vocabIds: ['u-menya-net', 'vremya', 'rynok', 'tsena', 'rubl'],
              patternIds: ['u-menya-net-x'],
              sentences: [
                { text: 'У меня нет времени.', translation: 'I do not have time.', vocabIds: ['u-menya-net', 'vremya'] },
                { text: 'У меня нет денег.', translation: 'I do not have money.', vocabIds: ['u-menya-net', 'dengi'] },
                { text: 'Какая цена на рынке?', translation: 'What is the price at the market?', vocabIds: ['kakoy', 'tsena', 'rynok'] },
                { text: 'Это стоит десять рублей.', translation: 'This costs ten rubles.', vocabIds: ['eto', 'stoit', 'desyat', 'rubl'] },
              ],
            },
          ],
        },
      ],
    },
    {
      id: 'u12',
      title: 'Mastering the cases',
      description: 'The instrumental case, verb aspect in the past tense, and motion verbs with prefixes',
      level: 'B1',
      skills: [
        {
          id: 'u12s1',
          title: 'Instrumental case',
          icon: 'users',
          lessons: [
            {
              id: 'u12s1l1',
              title: 'With someone',
              vocabIds: ['s-with', 'kem'],
              patternIds: ['rabotayu-x'],
              sentences: [
                { text: 'Я иду с другом.', translation: 'I am going with a friend.', vocabIds: ['idti', 's-with', 'drug'] },
                { text: 'С кем ты говоришь?', translation: 'Who are you speaking with?', vocabIds: ['kem', 'govoryu'] },
                { text: 'Я работаю врачом.', translation: 'I work as a doctor.', vocabIds: ['rabotayu', 'vrach'] },
                { text: 'Брат идёт с другом.', translation: 'Brother is going with a friend.', vocabIds: ['brat', 'idti', 's-with', 'drug'] },
              ],
            },
            {
              id: 'u12s1l2',
              title: 'Working as',
              vocabIds: ['moy'],
              patternIds: ['rabotayu-x'],
              sentences: [
                { text: 'Мой брат работает учителем.', translation: 'My brother works as a teacher.', vocabIds: ['moy', 'brat', 'rabotayu', 'uchitel'] },
                { text: 'Она работает инженером.', translation: 'She works as an engineer.', vocabIds: ['ona', 'rabotayu', 'inzhener'] },
                { text: 'Он будет работать директором.', translation: 'He will work as a director.', vocabIds: ['on', 'budu', 'rabotayu', 'direktor'] },
                { text: 'Мой друг работает врачом.', translation: 'My friend works as a doctor.', vocabIds: ['moy', 'drug', 'rabotayu', 'vrach'] },
              ],
            },
          ],
        },
        {
          id: 'u12s2',
          title: 'Verb aspect — past tense',
          icon: 'clock',
          lessons: [
            {
              id: 'u12s2l1',
              title: 'Finished actions',
              vocabIds: ['prochitat', 'napisat'],
              sentences: [
                { text: 'Я прочитал книгу.', translation: 'I read the book (and finished it).', vocabIds: ['prochitat', 'kniga'] },
                { text: 'Она написала книгу.', translation: 'She wrote a book.', vocabIds: ['napisat', 'kniga'] },
                { text: 'Сегодня я написал книгу.', translation: 'Today I wrote a book.', vocabIds: ['segodnya', 'napisat', 'kniga'] },
                { text: 'Друг прочитал книгу.', translation: 'A friend read the book.', vocabIds: ['drug', 'prochitat', 'kniga'] },
              ],
            },
            {
              id: 'u12s2l2',
              title: 'In progress vs. finished',
              vocabIds: ['posmotret-pf'],
              sentences: [
                { text: 'Я смотрел фильм.', translation: 'I was watching a movie.', vocabIds: ['smotret', 'film'] },
                { text: 'Я посмотрел фильм.', translation: 'I watched the whole movie.', vocabIds: ['posmotret-pf', 'film'] },
                { text: 'Она читала книгу.', translation: 'She was reading a book.', vocabIds: ['chitat', 'kniga'] },
                { text: 'Она прочитала книгу.', translation: 'She finished reading the book.', vocabIds: ['prochitat', 'kniga'] },
              ],
            },
          ],
        },
        {
          id: 'u12s3',
          title: 'Motion verbs with prefixes',
          icon: 'map-pin',
          lessons: [
            {
              id: 'u12s3l1',
              title: 'Setting off & arriving',
              vocabIds: ['poyti', 'priyti', 'domoy', 'kuda'],
              sentences: [
                { text: 'Я пошёл домой.', translation: 'I set off for home.', vocabIds: ['poyti', 'domoy'] },
                { text: 'Он пришёл домой.', translation: 'He arrived home.', vocabIds: ['priyti', 'domoy'] },
                { text: 'Куда ты пошёл?', translation: 'Where did you go?', vocabIds: ['kuda', 'poyti'] },
                { text: 'Друг пришёл в школу.', translation: 'A friend arrived at school.', vocabIds: ['drug', 'priyti', 'shkola'] },
              ],
            },
            {
              id: 'u12s3l2',
              title: 'Leaving',
              vocabIds: ['uyti'],
              sentences: [
                { text: 'Она ушла домой.', translation: 'She left for home.', vocabIds: ['uyti', 'domoy'] },
                { text: 'Брат ушёл домой.', translation: 'Brother left for home.', vocabIds: ['brat', 'uyti', 'domoy'] },
                { text: 'Куда она ушла?', translation: 'Where did she go (leave to)?', vocabIds: ['kuda', 'uyti'] },
                { text: 'Друг ушёл, и я пошёл домой.', translation: 'A friend left, and I set off for home.', vocabIds: ['drug', 'uyti', 'poyti', 'domoy'] },
              ],
            },
          ],
        },
      ],
    },
    {
      id: 'u13',
      title: 'Real fluency',
      description: 'Conditional mood, participles, чтобы-clauses, and passive voice',
      level: 'B2',
      skills: [
        {
          id: 'u13s1',
          title: 'Conditional mood',
          icon: 'sparkles',
          lessons: [
            {
              id: 'u13s1l1',
              title: 'If... would',
              vocabIds: ['esli', 'by'],
              sentences: [
                { text: 'Если я знаю, я скажу.', translation: 'If I know, I will say.', vocabIds: ['esli', 'znayu', 'skazhi'] },
                { text: 'Я бы пошёл домой.', translation: 'I would go home.', vocabIds: ['by', 'poyti', 'domoy'] },
                { text: 'Если бы у меня было время, я бы читал.', translation: 'If I had time, I would read.', vocabIds: ['esli', 'by', 'vremya', 'chitat'] },
                { text: 'Она бы работала врачом.', translation: 'She would work as a doctor.', vocabIds: ['by', 'rabotayu', 'vrach'] },
              ],
            },
            {
              id: 'u13s1l2',
              title: 'Because & so that',
              vocabIds: ['potomu-chto', 'chtoby'],
              sentences: [
                { text: 'Я устал, потому что я работал.', translation: 'I am tired because I worked.', vocabIds: ['ustal', 'potomu-chto', 'rabotayu'] },
                { text: 'Я иду домой, чтобы спать.', translation: 'I am going home in order to sleep.', vocabIds: ['idti', 'domoy', 'chtoby', 'spat'] },
                { text: 'Она читает, чтобы знать.', translation: 'She reads in order to know.', vocabIds: ['chitat', 'chtoby', 'znayu'] },
                { text: 'Потому что я рад, я работаю.', translation: 'Because I am glad, I work.', vocabIds: ['potomu-chto', 'rad', 'rabotayu'] },
              ],
            },
          ],
        },
        {
          id: 'u13s2',
          title: 'Active participles',
          icon: 'users',
          lessons: [
            {
              id: 'u13s2l1',
              title: 'The person who works',
              vocabIds: ['chelovek', 'rabotayushchiy'],
              sentences: [
                { text: 'Человек, работающий здесь, — врач.', translation: 'The person working here is a doctor.', vocabIds: ['chelovek', 'rabotayushchiy', 'zdes', 'vrach'] },
                { text: 'Я знаю человека, работающего в школе.', translation: 'I know a person working at school.', vocabIds: ['znayu', 'chelovek', 'rabotayushchiy', 'shkola'] },
                { text: 'Учитель, работающий в школе, хороший.', translation: 'The teacher working at school is good.', vocabIds: ['uchitel', 'rabotayushchiy', 'shkola', 'khorosho'] },
                { text: 'Друг, читающий книгу, там.', translation: 'The friend reading the book is there.', vocabIds: ['drug', 'chitayushchiy', 'kniga', 'tam'] },
              ],
            },
            {
              id: 'u13s2l2',
              title: 'The person who reads',
              vocabIds: ['chitayushchiy'],
              sentences: [
                { text: 'Человек, читающий книгу, — врач.', translation: 'The person reading the book is a doctor.', vocabIds: ['chelovek', 'chitayushchiy', 'kniga', 'vrach'] },
                { text: 'Я вижу человека, читающего книгу.', translation: 'I see a person reading a book.', vocabIds: ['videt', 'chelovek', 'chitayushchiy', 'kniga'] },
                { text: 'Дети, читающие книги, там.', translation: 'The children reading books are there.', vocabIds: ['deti', 'chitayushchiy', 'kniga', 'tam'] },
                { text: 'Это человек, читающий книгу.', translation: 'This is a person reading a book.', vocabIds: ['eto', 'chelovek', 'chitayushchiy', 'kniga'] },
              ],
            },
          ],
        },
        {
          id: 'u13s3',
          title: 'Passive voice',
          icon: 'home',
          lessons: [
            {
              id: 'u13s3l1',
              title: 'Open & closed',
              vocabIds: ['otkryt', 'zakryt'],
              sentences: [
                { text: 'Магазин открыт.', translation: 'The shop is open.', vocabIds: ['magazin', 'otkryt'] },
                { text: 'Школа закрыта.', translation: 'The school is closed.', vocabIds: ['shkola', 'zakryt'] },
                { text: 'Сегодня магазин закрыт.', translation: 'Today the shop is closed.', vocabIds: ['segodnya', 'magazin', 'zakryt'] },
                { text: 'Парк открыт.', translation: 'The park is open.', vocabIds: ['park', 'otkryt'] },
              ],
            },
            {
              id: 'u13s3l2',
              title: 'It is done',
              vocabIds: ['sdelano'],
              sentences: [
                { text: 'Это сделано.', translation: 'This is done.', vocabIds: ['eto', 'sdelano'] },
                { text: 'Работа сделана хорошо.', translation: 'The work is done well.', vocabIds: ['rabota', 'sdelano', 'khorosho'] },
                { text: 'Дом сделан хорошо.', translation: 'The house is built well.', vocabIds: ['dom', 'sdelano', 'khorosho'] },
                { text: 'Это плохо сделано.', translation: 'This is badly done.', vocabIds: ['eto', 'plokho', 'sdelano'] },
              ],
            },
          ],
        },
      ],
    },
  ],
}
