import type { CourseId, Phrase, PhrasePack } from './types'

/**
 * Loecsen-style situational survival phrases — organised by real-life situation.
 * Single-word phrases that map to course vocab carry a `vocabId` so they can be
 * added to Practice; multi-word phrases are browse + listen only.
 *
 * Audio for every phrase is pre-generated by `scripts/gen-audio.py`, so the 🔊
 * button on each phrase uses a neural MP3 instead of Web Speech fallback.
 */
export const phrasebook: Record<CourseId, PhrasePack[]> = {
  ru: [
    {
      id: 'ru-essentials',
      title: 'Essentials',
      icon: 'hand',
      phrases: [
        { text: 'Привет', translation: 'Hi', vocabId: 'privet' },
        { text: 'Здравствуйте', translation: 'Hello (formal)', vocabId: 'zdravstvuyte' },
        { text: 'Спасибо', translation: 'Thank you', vocabId: 'spasibo' },
        { text: 'Пожалуйста', translation: 'Please / you are welcome', vocabId: 'pozhaluysta' },
        { text: 'Извините', translation: 'Excuse me / sorry', vocabId: 'izvinite' },
        { text: 'До свидания', translation: 'Goodbye', vocabId: 'do-svidaniya' },
      ],
    },
    {
      id: 'ru-cafe',
      title: 'At the café',
      icon: 'coffee',
      phrases: [
        { text: 'Я хочу кофе, пожалуйста.', translation: 'I want a coffee, please.' },
        { text: 'Можно воду?', translation: 'May I have water?' },
        { text: 'Сколько это стоит?', translation: 'How much is it?' },
        { text: 'Счёт, пожалуйста.', translation: 'The bill, please.' },
      ],
    },
    {
      id: 'ru-help',
      title: 'Getting help',
      icon: 'life-buoy',
      phrases: [
        { text: 'Вы говорите по-английски?', translation: 'Do you speak English?' },
        { text: 'Я не понимаю.', translation: 'I do not understand.' },
        { text: 'Помогите, пожалуйста!', translation: 'Help, please!' },
        { text: 'Где туалет?', translation: 'Where is the toilet?' },
      ],
    },
    {
      id: 'ru-food',
      title: 'Food & shopping',
      icon: 'shopping-cart',
      phrases: [
        { text: 'Хлеб', translation: 'Bread', vocabId: 'khleb' },
        { text: 'Сыр', translation: 'Cheese', vocabId: 'syr' },
        { text: 'Яблоко', translation: 'Apple', vocabId: 'yabloko' },
        { text: 'Молоко', translation: 'Milk', vocabId: 'moloko' },
        { text: 'Мне нужен хлеб.', translation: 'I need bread.' },
        { text: 'Это вкусно!', translation: 'This is delicious!' },
      ],
    },
    {
      id: 'ru-travel',
      title: 'Travel',
      icon: 'map-pin',
      phrases: [
        { text: 'Где метро?', translation: 'Where is the metro?' },
        { text: 'Вокзал далеко?', translation: 'Is the train station far?' },
        { text: 'Я иду домой.', translation: 'I am going home.' },
        { text: 'Можно такси?', translation: 'Can I have a taxi?' },
        { text: 'Сколько до центра?', translation: 'How much to the centre?' },
      ],
    },
    {
      id: 'ru-emergency',
      title: 'Emergency',
      icon: 'phone',
      phrases: [
        { text: 'Помогите!', translation: 'Help!' },
        { text: 'Полиция!', translation: 'Police!' },
        { text: 'Где больница?', translation: 'Where is the hospital?' },
        { text: 'Вызовите скорую.', translation: 'Call an ambulance.' },
        { text: 'Я потерялся.', translation: 'I am lost.' },
      ],
    },
    {
      id: 'ru-education',
      title: 'Education',
      icon: 'book-open',
      phrases: [
        { text: 'Где библиотека?', translation: 'Where is the library?' },
        { text: 'Я учусь здесь.', translation: 'I study here.' },
        { text: 'Это книга.', translation: 'This is a book.' },
        { text: 'Я не понял.', translation: 'I did not understand.' },
        { text: 'Повторите, пожалуйста.', translation: 'Repeat, please.' },
      ],
    },
  ],
  es: [
    {
      id: 'es-essentials',
      title: 'Essentials',
      icon: 'hand',
      phrases: [
        { text: 'Hola', translation: 'Hello', vocabId: 'hola' },
        { text: 'Gracias', translation: 'Thank you', vocabId: 'gracias' },
        { text: 'Por favor', translation: 'Please', vocabId: 'por-favor' },
        { text: 'Perdón', translation: 'Excuse me / sorry', vocabId: 'perdon' },
        { text: 'Adiós', translation: 'Goodbye', vocabId: 'adios' },
      ],
    },
    {
      id: 'es-cafe',
      title: 'At the café',
      icon: 'coffee',
      phrases: [
        { text: 'Quiero un café, por favor.', translation: 'I want a coffee, please.' },
        { text: '¿Me da agua?', translation: 'May I have water?' },
        { text: '¿Cuánto cuesta?', translation: 'How much is it?' },
        { text: 'La cuenta, por favor.', translation: 'The bill, please.' },
      ],
    },
    {
      id: 'es-help',
      title: 'Getting help',
      icon: 'life-buoy',
      phrases: [
        { text: '¿Habla inglés?', translation: 'Do you speak English?' },
        { text: 'No entiendo.', translation: 'I do not understand.' },
        { text: '¡Ayuda, por favor!', translation: 'Help, please!' },
        { text: '¿Dónde está el baño?', translation: 'Where is the toilet?' },
      ],
    },
    {
      id: 'es-food',
      title: 'Food & shopping',
      icon: 'shopping-cart',
      phrases: [
        { text: 'Pan', translation: 'Bread', vocabId: 'pan' },
        { text: 'Queso', translation: 'Cheese', vocabId: 'queso' },
        { text: 'Manzana', translation: 'Apple', vocabId: 'manzana' },
        { text: 'Leche', translation: 'Milk', vocabId: 'leche' },
        { text: 'Necesito pan.', translation: 'I need bread.' },
        { text: '¡Está rico!', translation: 'This is delicious!' },
      ],
    },
    {
      id: 'es-travel',
      title: 'Travel',
      icon: 'map-pin',
      phrases: [
        { text: '¿Dónde está el metro?', translation: 'Where is the metro?' },
        { text: '¿Está lejos la estación?', translation: 'Is the station far?' },
        { text: 'Voy a casa.', translation: 'I am going home.' },
        { text: '¿Me puede llamar un taxi?', translation: 'Can you call me a taxi?' },
        { text: '¿Cuánto cuesta al centro?', translation: 'How much to the centre?' },
      ],
    },
    {
      id: 'es-emergency',
      title: 'Emergency',
      icon: 'phone',
      phrases: [
        { text: '¡Ayuda!', translation: 'Help!' },
        { text: '¡Policía!', translation: 'Police!' },
        { text: '¿Dónde está el hospital?', translation: 'Where is the hospital?' },
        { text: 'Llame una ambulancia.', translation: 'Call an ambulance.' },
        { text: 'Estoy perdido.', translation: 'I am lost.' },
      ],
    },
    {
      id: 'es-education',
      title: 'Education',
      icon: 'book-open',
      phrases: [
        { text: '¿Dónde está la biblioteca?', translation: 'Where is the library?' },
        { text: 'Estudio aquí.', translation: 'I study here.' },
        { text: 'Este es un libro.', translation: 'This is a book.' },
        { text: 'No entiendo.', translation: 'I do not understand.' },
        { text: 'Repita, por favor.', translation: 'Repeat, please.' },
      ],
    },
  ],
}

/** Phrases whose vocabId matches one of the given ids, in input order. Coverage is
 *  sparse (most multi-word phrases carry no vocabId) — an empty/partial result is
 *  expected, not an error. */
export function phrasesForVocabIds(course: CourseId, vocabIds: string[]): Phrase[] {
  const byVocabId = new Map<string, Phrase>()
  for (const pack of phrasebook[course] ?? []) {
    for (const phrase of pack.phrases) {
      if (phrase.vocabId && !byVocabId.has(phrase.vocabId)) byVocabId.set(phrase.vocabId, phrase)
    }
  }
  return vocabIds.map((id) => byVocabId.get(id)).filter((p): p is Phrase => p !== undefined)
}
